// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 1998-2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeDynTree';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeDynTree';
}
window.onload=initializeAll;
function errorTrap(){return true;}
window.onerror=errorTrap;

function getIndent (theItem)
{
	if(!theItem.id)return -1;
	var end=theItem.id.indexOf("SXE");
	if (end==-1 || theItem.id.indexOf("PH")!=-1) return -1;
	return parseInt(theItem.id.substring (1, end));
}

var waitList="";
function waitForElement(elStr)
{
	var fr=window.frames['dyntree_frame'];
	var ld=fr.document.getElementById('docLoaded');
	if(!ld||fr.document.dirty){setTimeout("waitForElement('"+elStr+"')",50);return;}
	var el=document.getElementById(elStr+"SXCPH");
	if(el)el.style.display="none";
	var els=fr.document.getElementsByTagName('div');
	var i;
	for(i=0;i<els.length;i++)
	{
		if(els[i].id.indexOf('SXE')!=-1)
		{
			var sub=document.createElement('div');
			sub.className=els[i].className;
			sub.id=els[i].id;
			if(els[i].getAttribute('par'))sub.setAttribute('par',els[i].getAttribute('par'));
			sub.innerHTML=els[i].innerHTML;
			sub.style.display='none';
			if(els[i].id.indexOf('PH')!=-1){sub.style.marginLeft=els[i].style.marginLeft;}
			document.body.insertBefore(sub,el);
		}
	}
	onClicked(elStr);
	var sep=waitList.indexOf(';');
	if(sep!=-1){waitList=waitList.substring(sep+1);}
	processWaitList();
}

function switchVisibility(theItem,image,image2)
{
	if (theItem.style.display=="none")
	{
		theItem.style.display="block";
		if (image)image.src=imf+"/sxicon1.gif";
		if (image2&&image2.src&&image2.src.indexOf('sxicon2.gif')!=-1)image2.src=imf+"/sxicon3.gif";
	}
	else
	{
		theItem.style.display="none";
		if(image)image.src=imf+"/sxicon0.gif";
		if(image2&&image2.src&&image2.src.indexOf('sxicon3.gif')!=-1)image2.src=imf+"/sxicon2.gif";
	}
}

function addToWaitList (el)
{
	if(waitList.indexOf(el)!=-1)return;
	if(!waitList){waitList=el+';';processWaitList();}
	else waitList+=el+';';
}

function processWaitList()
{
	var sep=waitList.indexOf(';');
	if(sep==-1)return;
	var el=waitList.substring(0,sep);
	var ph=document.getElementById(el+"SXCPH");
	if(ph)ph.style.display="block";
	var fr=window.frames['dyntree_frame'];
	fr.document.dirty='true';
	fr.document.location=dynPref+el+"SXC.htm";
	setTimeout("waitForElement('"+el+"')",50);
}

function onClicked(elm,lev,el)
{
	if(!elm){elm="I"+lev+"SXE"+el;}
	var theItem=document.getElementById(elm+"SXC");
	if(dynLoad&&!theItem)
	{
		addToWaitList(elm);
		return;
	}
	var image=document.images ["M"+elm+"SXP"];
	var image2=null;
	if (bOpenIcon)image2=document.images ["N"+elm+"SXP"];
	var bShow=(theItem.style.display=="none");
	var fold=document.getElementById(elm+'SXP');
	if(bShow&&singleFolder&&fold&&fold.getAttribute('par'))
	{
		var els=document.getElementsByTagName('div');
		var i;
		for(i=0;i<els.length;i++)
		{
			if(els[i].getAttribute('par')&&els[i].getAttribute('par')==fold.getAttribute('par'))
			{
				var chel=els[i].id.substring(0,els[i].id.indexOf('SXP'));
				var ch=document.getElementById(chel+'SXC');
				if(ch&&ch.style.display!="none")onClicked(chel);
			}
		}
	}
	switchVisibility(theItem,image,image2);
	var elem=theItem.nextSibling;
	var tii=getIndent(theItem);
	while(elem)
	{
		var retVal=0;
		var tci=getIndent(elem);
		if (tci!=-1)
		{
			var bfold=(elem.id.indexOf("SXP")!=-1);
			if (tci == (tii + 1))
			{
				if (bfold)retVal=3;
				  else
					retVal=1;
			}
			else if(tci>(tii+1))retVal=2;
			else if(tci==tii && !bfold)retVal=3;
			else break;
			if(bShow)
			{
				if(retVal==3)switchVisibility(elem,null,null);
			}
			else
			{
				elem.style.display="none";
				if(bfold)
				{
					document.images["M"+elem.id].src=imf+"/sxicon0.gif";
					if(bOpenIcon&&document.images["N"+elem.id].src&&document.images["N"+elem.id].src.indexOf('sxicon3.gif')!=-1)document.images["N"+elem.id].src=imf+"/sxicon2.gif";
				}
			}
		}
		elem=elem.nextSibling;
	}
	return elem;
}

function onExpandAll()
{
	var newSrc=imf+"/sxicon1.gif";
	var divColl=document.getElementsByTagName("DIV");
	var i;
	for (i=0;i<divColl.length;i++)
		{
		el=divColl[i];
		if(el.id&&el.id.indexOf('SX')!=-1)
		{
			el.style.display="block";
			if(el.id.indexOf("SXP")!=-1)
			{
				document.images["M"+el.id].src = newSrc;
				if(bOpenIcon&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('sxicon2.gif')!=-1)document.images["N"+el.id].src=imf+"/sxicon3.gif";
			}
		}
	}
}

function onCollapseAll()
{
	var newSrc=imf+"/sxicon0.gif" ;
	var divColl=document.getElementsByTagName("DIV");
	var i;
	for (i=0;i<divColl.length;i++)
	{
		var el=divColl[i];
		if(el.id&&el.id.indexOf('SX')!=-1)
		{
			if (el.id.indexOf("SXP")!=-1)
			{
				document.images["M"+el.id].src=newSrc;
				if (bOpenIcon&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('sxicon3.gif')!=-1)document.images["N"+el.id].src=imf+"/sxicon2.gif";
			}
			if(el.id.indexOf("SXC")!=-1||getIndent(el)>0)el.style.display="none";
		}
	}
}

function fixDate(date)
{
	var base=new Date (0);
	var off = base.getTime();
	if (off>0)date.setTime(date.getTime()-off);
}

function saveCookie()
{
	if (nDays > 0&&!dynLoad)
	{
		var now=new Date();
		fixDate(now);
		now.setTime(now.getTime()+nDays*24*60*60*1000);
		var strnow=now.toGMTString();
		var ckstr="";
		var str;
		ind=-1;
		var tempColl=document.getElementsByTagName("DIV");
		for(i=0;i<tempColl.length;i++)
		{
			var theItem=tempColl[i];
			if (theItem.id.indexOf("SXP")!=-1)
			{
				var sxc=document.getElementById(theItem.id.substring(0,theItem.id.indexOf("SXP"))+"SXC");
				if (sxc.style.display=="none")ckstr+="0";
				else ckstr+="1";
			}
		}
		document.cookie="sxtree="+ckstr+"; expires="+strnow;
		document.cookie="sxpossaved=true; expires="+strnow;
	}
	return true;
}

function initializeDynTree()
{
	if(dynLoad)return;
	var nextFolder=null;
	var bIgnoredFolder=true;
	var sxpind=0;
	var state;
	var i;
	if (nDays>0)
	{
		var cks=document.cookie.split(';');
		for(i=0;i<cks.length;i++)
		{
			if(cks[i].indexOf("sxtree")!=-1)state=cks[i].substring(cks[i].indexOf("=")+1);
		}
	}
	var tempColl=document.getElementsByTagName("DIV");
	for (i=0;i<tempColl.length;i++)
	{
		var el=tempColl[i];
		if(el.id&&el.id.indexOf('SX')!=-1)
		{
			var ii=getIndent(el);
			if(el==nextFolder){bIgnoredFolder=true;}
			if(!state||nDays==0||document.cookie.indexOf("sxpossaved")==-1)
			{
				if((el.id.indexOf("SXC")!=-1&&ii==showLevel)||ii>showLevel)el.style.display="none";
			}
			else if(el.id.indexOf("SXP")!=-1)
			{
				var bset=false;
				if (bIgnoredFolder&&state.substr(sxpind,1)=="0")
				{
					var elid=el.id.substring(0,el.id.indexOf("SXP"));
					nextFolder=onClicked(elid);
					bIgnoredFolder=false;
					bset=true;
				}
				if(!bset&&bIgnoredFolder)
				{
					document.images["M"+el.id].src=imf+"/sxicon1.gif";
					if(bOpenIcon&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('sxicon2.gif')!=-1)document.images["N"+el.id].src=imf+"/sxicon3.gif";
				}
				sxpind++;
			}
		}
	}
	doAutoSync();
}

function expandTree(el)
{
	var retval=0;
	if(!el)return;
	if(el.id&&el.id.indexOf("SXP")!=-1)
	{
		expandTree(document.getElementById(el.getAttribute('par')));
		var ch=document.getElementById(el.id.substring(0,el.id.indexOf("SXP"))+"SXC");
		if(ch&&ch.style.display=="none")onClicked(el.id.substring(0,el.id.indexOf("SXP")));
		retval=1;
	}
	else if(el.id&&el.id.indexOf("SXC")!=-1)
	{
		expandTree(document.getElementById(el.id.substring(0,el.id.indexOf("SXC"))+"SXP"));
		retval=1;
	}
	else
	{
		if(el.id&&el.id.indexOf("SXR")!=-1)retval=1;
		if(expandTree(el.parentElement?el.parentElement:el.parentNode))retval=1;
	}
	return retval;
}

function fixUrl(url)
{
	var newUrl=unescape(url.toLowerCase());
	var ind=newUrl.indexOf('index.');
	if(ind!=-1)newUrl=newUrl.substr(0,ind);
	if(newUrl.length>0&&newUrl.substr(newUrl.length-1,1)=="/")newUrl=newUrl.substr(0,newUrl.length-1);
	return newUrl;
}

function synchronize(url)
{
	var lurl=fixUrl(url.href);
	var els=document.getElementsByTagName('a');
	var i;
	for(i=0;i<els.length;i++)
	{
		if(lurl==fixUrl(els[i].href)&&syncEl!=els[i])
		{
			if(expandTree (els[i].parentElement?els[i].parentElement:els[i].parentNode))
			{
				if(syncEl){syncEl.style.backgroundColor=document.body.bgColor?document.body.bgColor:'white';syncEl.innerHTML=syncEl.getAttribute('oldCode');}
				els[i].style.backgroundColor=syncBgColor;
				els[i].setAttribute('oldCode',els[i].innerHTML);
				els[i].innerHTML='['+els[i].innerHTML+']';
				syncEl=els[i];
				break;
			}
		}
	}
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}