<link rel="stylesheet" type="text/css" href="rs/homedepot/hdstyle.css">
<table cellpadding=0 cellspacing=0 border=0 width=776 align=center>
	<tr>
		<td width=36><a href="http://www.homedepot.com"><img src="rs/homedepot/top_left_header_image.gif" width=36 height=84 border=0></a></td>
		<td width=740>
		<table cellpadding=0 cellspacing=0 border=0 align=center width=740 valign=top>
			<tr>
				<td width=46><a href="http://www.homedepot.com"><img src="rs/homedepot/top_right_header_image.gif" width=46 height=60 border=0></a></td>
				<td valign=top>
				<table cellpadding=0 cellspacing=0 border=0 align=center width=900>
					<tr>
						<td class=TDheaderGRAYshadedBG5 colspan=3 height=36>&nbsp;&nbsp;&nbsp;&nbsp;Personal DISCernment Inventory</td>
					</tr>
					<tr>
						<td class=TDheaderGRAYshadedBG6 colspan=3 height=24>&nbsp;</td>
					</tr>
				</table>
				</td>
			</tr>
			<tr>
				<td colspan=2>
				<table cellpadding=0 cellspacing=0 border=0 width=946>
					<tr>
						<td class=GRAYcontentSHADEDbg width=736 height=24>&nbsp;&nbsp;</td>
						<td class=GRAYcontentSHADEDbg valign=bottom align=right width=4><img src="rs/homedepot/right_corner.gif" width=4 height=4></td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
</table>