<%
Response.Write "<html><body>"
Response.Write "<br>ALL_HTTP = " & Request.ServerVariables("ALL_HTTP")
Response.Write "<br>ALL_RAW = " & Request.ServerVariables("ALL_RAW")
Response.Write "<br>APPL_MD_PATH = " & Request.ServerVariables("APPL_MD_PATH")
Response.Write "<br>APPL_PHYSICAL_PATH = " & Request.ServerVariables("APPL_PHYSICAL_PATH")
Response.Write "<br>AUTH_PASSWORD = " & Request.ServerVariables("AUTH_PASSWORD")
Response.Write "<br>AUTH_TYPE = " & Request.ServerVariables("AUTH_TYPE")
Response.Write "<br>AUTH_USER = " & Request.ServerVariables("AUTH_USER")
Response.Write "<br>CERT_COOKIE = " & Request.ServerVariables("CERT_COOKIE")
Response.Write "<br>CERT_FLAGS = " & Request.ServerVariables("CERT_FLAGS")
Response.Write "<br>CERT_ISSUER = " & Request.ServerVariables("CERT_ISSUER")
Response.Write "<br>CERT_KEYSIZE = " & Request.ServerVariables("CERT_KEYSIZE")
Response.Write "<br>CERT_SECRETKEYSIZE = " & Request.ServerVariables("CERT_SECRETKEYSIZE")
Response.Write "<br>CERT_SERIALNUMBER = " & Request.ServerVariables("CERT_SERIALNUMBER")
Response.Write "<br>CERT_SERVER_ISSUER = " & Request.ServerVariables("CERT_SERVER_ISSUER")
Response.Write "<br>CERT_SERVER_SUBJECT = " & Request.ServerVariables("CERT_SERVER_SUBJECT")
Response.Write "<br>CERT_SUBJECT = " & Request.ServerVariables("CERT_SUBJECT")
Response.Write "<br>CONTENT_LENGTH = " & Request.ServerVariables("CONTENT_LENGTH")
Response.Write "<br>CONTENT_TYPE = " & Request.ServerVariables("CONTENT_TYPE")
Response.Write "<br>GATEWAY_INTERFACE = " & Request.ServerVariables("GATEWAY_INTERFACE")
Response.Write "<br>HTTP_ACCEPT = " & Request.ServerVariables("HTTP_ACCEPT")
Response.Write "<br>HTTP_ACCEPT_LANGUAGE = " & Request.ServerVariables("HTTP_ACCEPT_LANGUAGE")
Response.Write "<br>HTTP_COOKIE = " & Request.ServerVariables("HTTP_COOKIE")
Response.Write "<br>HTTP_REFERER = " & Request.ServerVariables("HTTP_REFERER")
Response.Write "<br>HTTP_USER_AGENT = " & Request.ServerVariables("HTTP_USER_AGENT")
Response.Write "<br>HTTPS = " & Request.ServerVariables("HTTPS")
Response.Write "<br>HTTPS_KEYSIZE = " & Request.ServerVariables("HTTPS_KEYSIZE")
Response.Write "<br>HTTPS_SECRETKEYSIZE = " & Request.ServerVariables("HTTPS_SECRETKEYSIZE")
Response.Write "<br>HTTPS_SERVER_ISSUER = " & Request.ServerVariables("HTTPS_SERVER_ISSUER")
Response.Write "<br>HTTPS_SERVER_SUBJECT = " & Request.ServerVariables("HTTPS_SERVER_SUBJECT")
Response.Write "<br>INSTANCE_ID = " & Request.ServerVariables("INSTANCE_ID")
Response.Write "<br>INSTANCE_META_PATH = " & Request.ServerVariables("INSTANCE_META_PATH")
Response.Write "<br>LOCAL_ADDR = " & Request.ServerVariables("LOCAL_ADDR")
Response.Write "<br>LOGON_USER = " & Request.ServerVariables("LOGON_USER")
Response.Write "<br>PATH_INFO = " & Request.ServerVariables("PATH_INFO")
Response.Write "<br>PATH_TRANSLATED = " & Request.ServerVariables("PATH_TRANSLATED")
Response.Write "<br>QUERY_STRING = " & Request.ServerVariables("QUERY_STRING")
Response.Write "<br>REMOTE_ADDR = " & Request.ServerVariables("REMOTE_ADDR")
Response.Write "<br>REMOTE_HOST = " & Request.ServerVariables("REMOTE_HOST")
Response.Write "<br>REMOTE_USER = " & Request.ServerVariables("REMOTE_USER")
Response.Write "<br>REQUEST_METHOD = " & Request.ServerVariables("REQUEST_METHOD")
Response.Write "<br>SCRIPT_NAME = " & Request.ServerVariables("SCRIPT_NAME")
Response.Write "<br>SERVER_NAME = " & Request.ServerVariables("SERVER_NAME")
Response.Write "<br>SERVER_PORT = " & Request.ServerVariables("SERVER_PORT")
Response.Write "<br>SERVER_PORT_SECURE = " & Request.ServerVariables("SERVER_PORT_SECURE")
Response.Write "<br>SERVER_PROTOCOL = " & Request.ServerVariables("SERVER_PROTOCOL")
Response.Write "<br>SERVER_SOFTWARE = " & Request.ServerVariables("SERVER_SOFTWARE")
Response.Write "<br>URL = " & Request.ServerVariables("URL")
Response.Write "</body></html>"
%>

