// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeDynTree';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeDynTree';
}
window.onload=initializeAll;
function errorTrap(){return true;}
window.onerror=errorTrap;

function getIndent (theItem)
	{
	if(!theItem.id)return -1;
	end = theItem.id.indexOf ("SXE") ;
	if (end == -1)
		return -1 ;
	return parseInt (theItem.id.substring (1, end)) ;
	}

function getIndex (el)
	{
	ind = -1 ;
	tempColl = document.getElementsByTagName ("DIV") ;
	for (i = 0 ; i < tempColl.length ; i++)
		{
		var theItem = tempColl [i] ;
		if (theItem.id == el)
			{
			ind = i ;
			break ;
			}
		}
	return ind ;
	}

function setPosition ()
	{
	var tp=document.getElementById ('TP');
	var nextY = tp.style.pixelTop+15;
	var baseX = tp.style.pixelLeft;
	var i;
	var tempColl = document.getElementsByTagName ("DIV");
	for (i = 0 ; i < tempColl.length ; i++)
		{
		theItem = tempColl[i];
		if (theItem.id.indexOf('SX')!=-1)
			{
			if (theItem.style.visibility != "hidden")
				{
				theItem.style.pixelTop = nextY ;				
				nextY += theItem.style.pixelHeight ;
				}
			theItem.style.pixelLeft = baseX;
			}
		}
	bel = document.getElementById("below") ;
	if (bel) {bel.style.pixelTop = nextY ; bel.style.pixelLeft = baseX;}
	}

function initializeDynTree ()
	{
	var nextind=0;
	var sxpind=0;
	var state;
	var i;
	if (nDays > 0)
		{
		cks = document.cookie.split (';');
		for (i = 0 ; i < cks.length ; i++)
			{
			if (cks [i].indexOf ("sxtree") != -1) state=cks[i].substring (cks[i].indexOf ("=") + 1);
			}
		divColl = document.getElementsByTagName ("DIV") ;
		for (i = 0 ; i < divColl.length ; i++)
			{
			if (divColl[i].id.indexOf("SX")!=-1)divColl[i].style.visibility = "visible";
			}
		setPosition ();
		}
	var tempColl = document.getElementsByTagName ("DIV");
	for (i = 0 ; i < tempColl.length ; i++)
		{
		theItem = tempColl[i];
		if(theItem.id&&theItem.id.indexOf('SX')!=-1)
			{
			ii = getIndent (theItem) ;
			if (!state || nDays == 0 || document.cookie.indexOf ("sxpossaved") == -1)
				{
				if ((theItem.id.indexOf ("SXC") != -1 && ii == showLevel) || ii > showLevel)
					theItem.style.visibility = "hidden" ;
				else
					theItem.style.visibility = "visible";
				}
			  else if (theItem.id.indexOf ("SXP") != -1)
				{
				var bset = false;
				if (i >= nextind && state.substr (sxpind,1) == "0")
					{
					var elid = theItem.id.substring (0,theItem.id.indexOf ("SXP"));
					nextind = onClicked (elid);
					bset = true;
					}

				if (!bset && i >= nextind)
					{
					theItem.document.images ["M"+theItem.id].src = imf + "/sxicon1.gif" ;
					if (bOpenIcon&&theItem.document.images ["N"+theItem.id].src&&theItem.document.images ["N"+theItem.id].src.indexOf('sxicon2.gif')!=-1) theItem.document.images ["N"+theItem.id].src = imf + "/sxicon3.gif"  ;
					}
				sxpind++;
				}
			}
		}
	setPosition () ;
	doAutoSync();
	}

function onClickedImpl(el)
{
	var theItem = document.getElementById (el + "SXC") ;
	var image = document.images ["M"+el+"SXP"] ;

	var image2 = null ;
	if (bOpenIcon)
		image2 = document.images ["N"+el+"SXP"] ;

	var bShow = (theItem.style.visibility == "hidden") ;

	var fold=document.getElementById(el+'SXP');
	if(bShow&&singleFolder&&fold&&fold.getAttribute('par'))
	{
		var els=document.getElementsByTagName('div');
		var i;
		for(i=0;i<els.length;i++)
		{
			if(els[i].getAttribute('par')&&els[i].getAttribute('par')==fold.getAttribute('par'))
			{
				var chel=els[i].id.substring(0,els[i].id.indexOf('SXP'));
				var ch=document.getElementById(chel+'SXC');
				if(ch&&ch.style.visibility!="hidden")onClicked(chel);
			}
		}
	}

	switchVisibility (theItem, image, image2)

	var ind = getIndex (theItem.id) + 1 ;
	tempColl = document.getElementsByTagName ("DIV") ;
	while (ind != -1 && ind < tempColl.length)
		{
		var retVal = 0 ;
		elem = tempColl [ind] ;
		if(elem.id&&elem.id.indexOf('SX')!=-1)
			{
			var tci = getIndent (elem) ;
			var tii = getIndent (theItem) ;
			var bfold = (elem.id.indexOf ("SXP") != -1) ;
			if (tci == (tii + 1))
				{
				if (bfold)
					retVal = 3 ;
				  else
					retVal = 1 ;
				}
			  else if (tci > (tii + 1))
				retVal = 2 ;
			  else if (tci == tii && !bfold)
				retVal = 3 ;
			  else
				break ;
			if (bShow)
				{
				if (retVal == 3)
					switchVisibility (elem, null, null) ;
				}
			  else
				{
				elem.style.visibility = "hidden" ;
				if (bfold)
					{
					document.images ["M"+elem.id].src = imf + "/sxicon0.gif" ;
					if (bOpenIcon&&document.images["N"+elem.id].src&&document.images["N"+elem.id].src.indexOf('sxicon3.gif')!=-1) document.images["N"+elem.id].src = imf + "/sxicon2.gif" ;
					}
				}
			}
		ind++ ;
		}
	return ind;
}

function onClicked (elm,lev,el)
	{
	if(!elm){elm="I"+lev+"SXE"+el;}
	var ind=onClickedImpl(elm);
	setPosition () ;
	saveCookieV4();
	return ind;
	}

function switchVisibility (theItem, image, image2)
	{
	if (theItem.style.visibility == "hidden")
		{
		theItem.style.visibility = "visible" ;
		if (image)
			image.src = imf + "/sxicon1.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon2')!=-1)
			image2.src = imf + "/sxicon3.gif" ;
		}
	  else
		{
		theItem.style.visibility = "hidden" ;
		if (image)
			image.src = imf + "/sxicon0.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon3')!=-1)
			image2.src = imf + "/sxicon2.gif" ;
		}
	}

function onExpandAll ()
	{
	newSrc = imf + "/sxicon1.gif" ;
	divColl = document.getElementsByTagName ("DIV") ;
	for (i = 0 ; i < divColl.length ; i++)
		{
		el = divColl[i] ;
		if (el.id.indexOf("SX")!=-1)
			{
			el.style.visibility = "visible";
			if (el.id.indexOf ("SXP") != -1)
				{
				document.images["M"+el.id].src = newSrc ;
				if (bOpenIcon&&document.images["N"+el.id].src&&document.images["N"+el.id].src.indexOf('sxicon2.gif')!=-1)
					document.images["N"+el.id].src = imf + "/sxicon3.gif" ;
				}
			}
		}
	setPosition ();
	saveCookieV4();
	}

function onCollapseAll ()
	{
	newSrc = imf + "/sxicon0.gif" ;

	divColl = document.getElementsByTagName ("DIV") ;
	for (i = 0 ; i < divColl.length ; i++)
		{
		el = divColl[i] ;
		if (el.id.indexOf ("SXP") != -1)
			{
			document.images ["M"+el.id].src = newSrc ;
			if (bOpenIcon&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indexOf('sxicon3.gif')!=-1)
				document.images ["N"+el.id].src = imf + "/sxicon2.gif" ;
			}
		if (el.id.indexOf ("SXC") != -1 || getIndent (el) > 0)
			el.style.visibility = "hidden" ;
		}
	setPosition ();
	saveCookieV4();
	}

function fixDate(date)
	{
	var base = new Date (0) ;
	var off = base.getTime () ;
	if (off > 0)
		date.setTime (date.getTime () - off) ;
	}

function saveCookie()
{
}

function saveCookieV4()
{
	if (nDays > 0)
		{
		var now = new Date () ;
		fixDate (now) ;
		now.setTime (now.getTime () + nDays * 24 * 60 * 60 * 1000) ;
		var strnow = now.toGMTString();

		var ckstr="";
		var str;
		ind = -1 ;
		tempColl = document.getElementsByTagName ("DIV") ;
		for (i = 0 ; i < tempColl.length ; i++)
			{
			var theItem = tempColl [i] ;
			if (theItem.id.indexOf ("SXP") != -1)
				{
				var sxc = document.getElementById (theItem.id.substring (0, theItem.id.indexOf ("SXP")) + "SXC") ;
				if (sxc.style.visibility=="hidden")
					ckstr += "0";
				  else
					ckstr += "1";
				}
			}
		document.cookie = "sxtree="+ckstr+"; expires="+strnow ;
		document.cookie = "sxpossaved=true; expires="+strnow ;
		}

	return true;
}

function expandTree(el)
{
	var retval=0;
	if(!el)return;
	if(el.id&&el.id.indexOf("SXP")!=-1)
	{
		expandTree(document.getElementById(el.par));
		var ch=document.getElementById(el.id.substring(0,el.id.indexOf("SXP"))+"SXC");
		if(ch&&ch.style.visibility=="hidden")onClicked(el.id.substring(0,el.id.indexOf("SXP")));
		retval=1;
	}
	else if(el.id&&el.id.indexOf("SXC")!=-1)
	{
		expandTree(document.getElementById(el.id.substring(0,el.id.indexOf("SXC"))+"SXP"));
		retval=1;
	}
	else
	{
		if(el.id&&el.id.indexOf("SXR")!=-1)retval=1;
		if(expandTree(el.offsetParent))retval=1;
	}
	return retval;
}

function fixUrl(url)
{
	var newUrl=unescape(url.toLowerCase());
	var ind=newUrl.indexOf('index.');
	if(ind!=-1)newUrl=newUrl.substr(0,ind);
	if(newUrl.length>0&&newUrl.substr(newUrl.length-1,1)=="/")newUrl=newUrl.substr(0,newUrl.length-1);
	return newUrl;
}

function synchronize(url)
{
	var surl=new String(url);
	var lurl=fixUrl(surl);
	var els=document.getElementsByTagName('a');
	var i;
	for(i=0;i<els.length;i++)
	{
		if(lurl==fixUrl(els[i].href)&&syncEl!=els[i])
		{
			if(expandTree (els[i].offsetParent))
			{
				if(syncEl)syncEl.style.backgroundColor=document.body.bgColor?document.body.bgColor:'white';
				els[i].style.backgroundColor=syncBgColor;
				syncEl=els[i];
				break;
			}
		}
	}
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}