// script generated by Xtreeme SiteXpert
// sitemap and search engine creator
// http://www.xtreeme.com/sitexpert
// Copyright(C) 1998-2002 Xtreeme GmbH

if (!document.loadHandlers)
{
	document.loadHandlers=new Array();
	document.loadHandlers[0]='initializeDynTree';
	document.lastLoadHandler=0;
}
else
{
	document.lastLoadHandler++;
	document.loadHandlers[document.lastLoadHandler]='initializeDynTree';
}
window.onload=initializeAll;
function errorTrap(){return true;}
window.onerror=errorTrap;

function getIndent (theItem)
	{
	if(!theItem.id)return -1;
	end = theItem.id.indexOf ("SXE") ;
	if (end == -1)
		return -1 ;
	return parseInt (theItem.id.substring (1, end)) ;
	}

function getIndexNS (el)
	{
	var i;
	ind = -1 ;
	for (i = 0 ; i < document.layers.length ; i++)
		{
		var theItem = document.layers [i] ;
		if (theItem == el)
			{
			ind = i ;
			break ;
			}
		}
	return ind ;
	}

function setPosition ()
	{
	document.layers [firstItem].pageY = document.TP.pageY + 15;
	document.layers [firstItem].pageX = document.TP.pageX;
	nextY = document.layers [firstItem].pageY + document.layers [firstItem].document.height ;
	var i;
	for (i = firstItem + 1 ; i <= lastItem && i < document.layers.length ; i++)
		{
		theItem = document.layers [i] ;
		if (theItem.visibility != "hide")
			{
			theItem.pageY = nextY ;
			nextY += theItem.document.height ;
			}
		theItem.pageX = document.TP.pageX;
		}
	bel = document.layers["below"] ;
	if (bel) {bel.pageY = nextY ; bel.pageX=document.TP.pageX;}
	}

function initializeDynTree ()
	{
	if(dynLoad)return;
	if (IE4)
		{
		firstItem = getIndexIE (SXR) ;
		lastItem = getIndexIE (eval(li)) ;
		}
	if (NS4)
		{
		firstItem = getIndexNS (document.SXR) ;
		lastItem = getIndexNS (eval("document."+li)) ;
		for (i = firstItem ; i <= lastItem && i < document.layers.length ; i++)
			document.layers [i].visibility = "show" ;
		setPosition () ;
		}

	var nextind=0;
	var sxpind=0;
	var state;
	var i;
	if (nDays > 0)
		{
		cks = document.cookie.split (';');
		for (i = 0 ; i < cks.length ; i++)
			{
			if (cks [i].indexOf ("sxtree") != -1) state=cks[i].substring (cks[i].indexOf ("=") + 1);
			}
		}
	if (NS4)
		{
		for (i = 0 ; i < document.layers.length ; i++)
			{
			theItem = document.layers [i] ;
			ii = getIndent (theItem) ;
			if (!state || nDays == 0 || document.cookie.indexOf ("sxpossaved") == -1)
				{
				if ((theItem.id.indexOf ("SXC") != -1 && ii == showLevel) || ii > showLevel)
					theItem.visibility = "hide" ;
				}
			  else if (theItem.id.indexOf ("SXP") != -1)
				{
				var bset = false;
				if (i >= nextind && state.substr (sxpind,1) == "0")
					{
					var elid = theItem.id.substring (0,theItem.id.indexOf ("SXP"));
					nextind = onClickedNS (elid);
					bset = true;
					}

				if (!bset && i >= nextind)
					{
					theItem.document.images ["M"+theItem.id].src = imf + "/sxicon1.gif" ;
					if (bOpenIcon&&theItem.document.images ["N"+theItem.id].src&&theItem.document.images ["N"+theItem.id].src.indexOf('sxicon2.gif')!=-1) theItem.document.images ["N"+theItem.id].src = imf + "/sxicon3.gif" ;
					}
				sxpind++;
				}
			}
		setPosition () ;
		}
	  else
		{
		tempColl = document.all.tags ("DIV") ;
		for (i = 0 ; i < tempColl.length ; i++)
			{
			el = tempColl(i) ;
			if(el.id&&el.id.indexOf('SX')!=-1)
				{
				ii = getIndent (el) ;
				if (!state || nDays == 0 || document.cookie.indexOf ("sxpossaved") == -1)
					{
					if ((el.id.indexOf ("SXC") != -1 && ii == showLevel) || ii > showLevel)
						el.style.display = "none" ;
					}
				  else if (el.id.indexOf ("SXP") != -1)
					{
					var bset = false;
					if (i >= nextind && state.substr (sxpind,1) == "0")
						{
						var elid = el.id.substring (0,el.id.indexOf ("SXP"));
						nextind = onClickedIE (elid);
						bset = true;
						}

					if (!bset && i >= nextind)
						{
						document.images ["M"+el.id].src = imf + "/sxicon1.gif" ;
						if (bOpenIcon&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indexOf('sxicon2.gif')!=-1) document.images ["N"+el.id].src = imf + "/sxicon3.gif"  ;
						}
					sxpind++;
					}
				}
			}
		}
	doAutoSync();
	}

function onClicked (elm,lev,el)
	{
	if(!elm){elm="I"+lev+"SXE"+el;}
	var rv;
	if (!ver4||dynLoad) return rv;
	if (IE4)
		rv=onClickedIE(elm);
	  else
		rv=onClickedNS(elm);
	saveCookieV4();
	return rv;
	}

function switchVisibilityIE (theItem, image, image2)
	{
	if (theItem.style.display == "none")
		{
		theItem.style.display = "block" ;
		if (image)
			image.src = imf + "/sxicon1.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon2.gif')!=-1)
			image2.src = imf + "/sxicon3.gif" ;
		}
	  else
		{
		theItem.style.display = "none" ;
		if (image)
			image.src = imf + "/sxicon0.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon3.gif')!=-1)
			image2.src = imf + "/sxicon2.gif" ;
		}
	}

function onClickedIE (el)
	{
	theItem = eval (el + "SXC") ;
	image = document.images["M"+el+"SXP"] ;

	var image2 = null ;
	if (bOpenIcon)
		image2 = document.images["N"+el+"SXP"] ;

	var bShow = (theItem.style.display == "none") ;
	switchVisibilityIE (theItem, image, image2)

	var ind = getIndexIE (theItem) + 1 ;
	tempColl = document.all.tags("DIV") ;
	while (ind != -1 && ind < tempColl.length)
		{
		var retVal = 0 ;
		elem = tempColl (ind) ;
		if(elem.id&&elem.id.indexOf('SX')!=-1)
			{
			var tci = getIndent (elem) ;
			var tii = getIndent (theItem) ;
			var bfold = (elem.id.indexOf ("SXP") != -1) ;
			if (tci == (tii + 1))
				{
				if (bfold)
					retVal = 3 ;
				  else
					retVal = 1 ;
				}
			  else if (tci > (tii + 1))
				retVal = 2 ;
			  else if (tci == tii && !bfold)
				retVal = 3 ;
			  else
				break ;
			if (bShow)
				{
				if (retVal == 3)
					switchVisibilityIE (elem, null, null) ;
				}
			  else
				{
				elem.style.display = "none" ;
				if (bfold)
					{
					document.images["M"+elem.id].src = imf + "/sxicon0.gif" ;
					if (bOpenIcon&&document.images["N"+elem.id].src&&document.images["N"+elem.id].src.indexOf('sxicon3.gif')!=-1) document.images["N"+elem.id].src = imf + "/sxicon2.gif" ;
					}
				}
			}
		ind++ ;
		}
	return ind;
	}

function switchVisibilityNS (theItem, image, image2)
	{
	if (theItem.visibility == "hide")
		{
		theItem.visibility = "show" ;
		if (image)
			image.src = imf + "/sxicon1.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon2.gif')!=-1)
			image2.src = imf + "/sxicon3.gif" ;
		}
	  else
		{
		theItem.visibility = "hide" ;
		if (image)
			image.src = imf + "/sxicon0.gif" ;
		if (image2&&image2.src&&image2.src.indexOf('sxicon3.gif')!=-1)
			image2.src = imf + "/sxicon2.gif" ;
		}
	}

function onClickedNS (el)
	{
	theItem = eval ("document." + el + "SXC") ;
	image = eval ("document." + el + "SXP.document.images['M'+el+'SXP']") ;
	var image2 = null ;
	if (bOpenIcon)
		image2 = eval ("document." + el + "SXP.document.images['N'+el+'SXP']") ;
	var bShow = (theItem.visibility == "hide") ;
	switchVisibilityNS (theItem, image, image2) ;
	var ind = getIndexNS (theItem) + 1 ;
	while (ind != -1 && ind < document.layers.length)
		{
		var retVal = 0 ;
		elem = document.layers [ind] ;
		var tci = getIndent (elem) ;
		var tii = getIndent (theItem) ;
		var bfold = (elem.id.indexOf ("SXP") != -1) ;
		if (tci == (tii + 1))
			{
			if (bfold)
				retVal = 3 ;
			  else
				retVal = 1 ;
			}
		  else if (tci > (tii + 1))
			retVal = 2 ;
		  else if (tci == tii && !bfold)
			retVal = 3 ;
		  else
			break ;
		if (bShow)
			{
			if (retVal == 3)
				switchVisibilityNS (elem, null) ;
			}
		  else
			{
			elem.visibility = "hide" ;
			if (bfold)
				{
				elem.document.images ['M'+elem.id].src = imf + "/sxicon0.gif" ;
				if (bOpenIcon&&elem.document.images ['N'+elem.id].src&&elem.document.images ['N'+elem.id].src.indexOf('sxicon3.gif')!=-1)
					elem.document.images ['N'+elem.id].src = imf + "/sxicon2.gif" ;
				}
			}
		ind++ ;
		}
	setPosition () ;
	return ind;
	}

function onExpandAll ()
	{
	var i;
	newSrc = imf + "/sxicon1.gif" ;

	if (NS4)
		{
		for (i = firstItem ; i <= lastItem && i < document.layers.length ; i++)
			{
			theItem = document.layers [i] ;
			if (theItem.id.indexOf ("SXP") != -1)
				{
				theItem.document.images ["M"+theItem.id].src = newSrc ;
				if (bOpenIcon&&theItem.document.images ["N"+theItem.id].src&&theItem.document.images ["N"+theItem.id].src.indexOf('sxicon2.gif')!=-1)
					theItem.document.images ["N"+theItem.id].src = imf + "/sxicon3.gif" ;
				}
			theItem.visibility = "show" ;
			}

		setPosition ();
		}
	  else
		{
		divColl = document.all.tags ("DIV") ;
		for (i = firstItem ; i<= lastItem && i < divColl.length ; i++)
			{
			el = divColl(i) ;
			if(el.id&&el.id.indexOf('SX')!=-1)
				{
				el.style.display = "block";
				if (el.id.indexOf ("SXP") != -1)
					{
					document.images ["M"+el.id].src = newSrc ;
					if (bOpenIcon&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indexOf('sxicon2.gif')!=-1)
						document.images ["N"+el.id].src = imf + "/sxicon3.gif" ;
					}
				}
			}
		}
	saveCookieV4();
	}

function onCollapseAll ()
	{
	var i;
	newSrc = imf + "/sxicon0.gif" ;

	if (NS4)
		{
		for (i = firstItem ; i <= lastItem && i < document.layers.length ; i++)
			{
			theItem = document.layers [i] ;
			if (theItem.id.indexOf ("SXP") != -1)
				{
				theItem.document.images ["M"+theItem.id].src = newSrc ;
				if (bOpenIcon&&theItem.document.images ["N"+theItem.id].src&&theItem.document.images ["N"+theItem.id].src.indexOf('sxicon3.gif')!=-1)
					theItem.document.images ["N"+theItem.id].src = imf + "/sxicon2.gif" ;
				}
			if (theItem.id.indexOf ("SXC") != -1 || getIndent (theItem) > 0)
				theItem.visibility = "hide" ;
			}

		setPosition ();
		}
	  else
		{
		divColl = document.all.tags ("DIV") ;
		for (i = firstItem ; i <= lastItem && i < divColl.length ; i++)
			{
			el = divColl(i) ;
			if (el.id.indexOf ("SXP") != -1)
				{
				document.images ["M"+el.id].src = newSrc ;
				if (bOpenIcon&&document.images ["N"+el.id].src&&document.images ["N"+el.id].src.indoxOf('sxicon3.gif')!=-1)
					document.images ["N"+el.id].src = imf + "/sxicon2.gif" ;
				}
			if (el.id.indexOf ("SXC") != -1 || getIndent (el) > 0)
				el.style.display = "none" ;
			}
		}
	saveCookieV4();
	}

function fixDate(date)
	{
	var base = new Date (0) ;
	var off = base.getTime () ;
	if (off > 0)
		date.setTime (date.getTime () - off) ;
	}

function saveCookie()
{
}

function saveCookieV4()
	{
	var i;
	if (nDays > 0&&!dynLoad)
		{
		var now = new Date () ;
		fixDate (now) ;
		now.setTime (now.getTime () + nDays * 24 * 60 * 60 * 1000) ;
		var strnow = now.toGMTString();

		var ckstr="";
		var str;
		ind = -1 ;

		if (NS4)
			{
			for (i = firstItem ; i <= lastItem && i < document.layers.length ; i++)
				{
				var theItem = document.layers [i] ;
				if (theItem.id.indexOf ("SXP") != -1)
					{
					var sxc = eval ("document." + theItem.id.substring (0, theItem.id.indexOf ("SXP")) + "SXC") ;
					if (sxc.visibility=="hide")
						ckstr += "0";
					  else
						ckstr += "1";
					}
				}
			}
		  else
			{
			divColl = document.all.tags ("DIV") ;
			for (i = firstItem ; i <= lastItem && i < divColl.length ; i++)
				{
				var theItem = divColl(i) ;
				if (theItem.id.indexOf ("SXP") != -1)
					{
					var sxc = eval (theItem.id.substring (0, theItem.id.indexOf ("SXP")) + "SXC") ;
					if (sxc.style.display=="none")
						ckstr += "0";
					  else
						ckstr += "1";
					}
				}
			}
		document.cookie = "sxtree="+ckstr+"; expires="+strnow ;
		document.cookie = "sxpossaved=true; expires="+strnow ;
		}

	return true;
	}

function getParentNS(el)
{
	var els=document.layers;
	var i;
	var divs=new Array;
	for(i=0;i<els.length;i++)
	{
		var cel=els[i];
		if(cel.id&&cel.id.indexOf("SXP")!=-1)
		{
			var lev=getIndent(cel);
			divs[lev]=cel;
			if(el.id==cel.id)
			{
				if(lev==0){return null;}else {return divs[lev-1];}
			}
		}		
	}
	return null;
}

function expandTreeNS(el)
{
	var retval=0;
	if(!el)return;
	if(el.id&&el.id.indexOf("SXP")!=-1)
	{
		expandTreeNS(getParentNS(el));
		var ch=document.layers[el.id.substring(0,el.id.indexOf("SXP"))+"SXC"];
		if(ch&&ch.visibility=="hide")onClickedNS(el.id.substring(0,el.id.indexOf("SXP")));
		retval=1;
	}
	else if(el.id&&el.id.indexOf("SXC")!=-1)
	{
		expandTreeNS(document.layers[el.id.substring(0,el.id.indexOf("SXC"))+"SXP"]);
		retval=1;
	}
	return retval;
}

function fixUrl(url)
{
	var newUrl=unescape(url.toLowerCase());
	var ind=newUrl.indexOf('index.');
	if(ind!=-1)newUrl=newUrl.substr(0,ind);
	if(newUrl.length>0&&newUrl.substr(newUrl.length-1,1)=="/")newUrl=newUrl.substr(0,newUrl.length-1);
	return newUrl;
}

function synchronizeNS(url)
{
	var lurl=fixUrl(url.href);
	var els=document.layers;
	var i;
	for(i=0;i<els.length;i++)
	{
		var j;
		var aels=els[i].document.links;
		for(j=0;j<aels.length;j++)
		{
			if(lurl==fixUrl(aels[j].href)&&syncEl!=aels[j])
			{
				if(expandTreeNS(els[i]))
				{
					syncEl=aels[j];
					break;
				}
			}
		}
	}
}

function expandTreeIE(el)
{
	var retval=0;
	if(!el)return;
	if(el.id&&el.id.indexOf("SXP")!=-1)
	{
		if(el.par!='root')expandTreeIE(eval(el.par));
		var ch=eval(el.id.substring(0,el.id.indexOf("SXP"))+"SXC");
		if(ch&&ch.style.display=="none")onClicked(el.id.substring(0,el.id.indexOf("SXP")));
		retval=1;
	}
	else if(el.id&&el.id.indexOf("SXC")!=-1)
	{
		expandTreeIE(eval(el.id.substring(0,el.id.indexOf("SXC"))+"SXP"));
		retval=1;
	}
	else
	{
		if(el.id&&el.id.indexOf("SXR")!=-1)retval=1;
		if(expandTreeIE(el.parentElement))retval=1;
	}
	return retval;
}

function synchronizeIE(url)
{
	var lurl=fixUrl(url.href);
	var els=document.all.tags ("a");
	var i;
	for(i=0;i<els.length;i++)
	{

		if(lurl==fixUrl(els[i].href)&&syncEl!=els[i])
		{
			if(expandTreeIE(els[i].parentElement?els[i].parentElement:els[i].parentNode))
			{
				if(syncEl){syncEl.style.backgroundColor=document.body.bgColor?document.body.bgColor:'white';syncEl.innerHTML=syncEl.getAttribute('oldCode');}
				els[i].style.backgroundColor=syncBgColor;
				els[i].setAttribute('oldCode',els[i].innerHTML);
				els[i].innerHTML='['+els[i].innerHTML+']';
				syncEl=els[i];
				break;
			}
		}
	}
}

function synchronize(url)
{
	if (IE4){synchronizeIE(url);} else {synchronizeNS(url);}
}

function initializeAll()
{
	var i;
	for(i=0;i<=document.lastLoadHandler;i++)
	{
		eval(document.loadHandlers[i]+'();');
	}
}