<%@ Language=VBScript %>
<!--#INCLUDE FILE="include/CheckAdminLogin.asp" -->
<!--#INCLUDE FILE="../include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="/pdi/_system.css" type="text/css"><!-- system stylesheet must come before the reseller stylesheet -->
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/reseller.css" type="text/css">
	<!--#INCLUDE FILE="../include/head_stuff.asp" -->	
</head>
<body>
<!--#INCLUDE FILE="include/header.asp" -->
<div class="TopNav">
	<a href="../main.asp?res=<%=intResellerID%>">PDI Home</a>&nbsp;|
	<a href="../logout.asp?res=<%=intResellerID%>">Logout</a>&nbsp;
</div>
<div id="maincontent">
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Monday, March 04, 2002  19:27:54
	'* Copyright (c) 2002 Team Resources, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure ins_Company using ADO.
	'**********************************************************************************************************************************
	
	on error resume next
	
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	
	Dim bFilledOutProperly, strErrMsg
	
	
	Dim CompanyName
	Dim Address1
	Dim Address2
	Dim Address3
	Dim Address4
	Dim City
	Dim ProvinceID
	Dim PostalCode
	Dim CreatedBy
	
	Dim CompanyTypeID
	Dim OriginationCoID
	
	Dim CompanyID
	
	CompanyTypeID = 4
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
		  CompanyName = Request.Form("txtCompanyName")
	
		  Address1 = Request.Form("txtAddress1")
	
		  Address2 = Request.Form("txtAddress2")
	
		  Address3 = Request.Form("txtAddress3")
	
		  Address4 = Request.Form("txtAddress4")
	
		  City = Request.Form("txtCity")
	
		  ProvinceID = Request.Form("txtProvinceID")
	
		  PostalCode = Request.Form("txtPostalCode")
	
		  CreatedBy = Request.Cookies("UserID")
	
		 CompanyTypeID = Request.Form("txtCompanyTypeID")
	
		 OriginationCoID = CInt(Request.Form("txtOriginationCoID"))
		  
		  CompanyID = Request.Form("txtCompanyID")
	
	Else
	
		CreatedBy = Request.Cookies("UserID")
	
	End If
	
	AliasCompany = Trim(AliasCompany)
	CompanyName = Trim(CompanyName)
	Address1 = Trim(Address1)
	Address2 = Trim(Address2)
	Address3 = Trim(Address3)
	Address4 = Trim(Address4)
	City = Trim(City)
	ProvinceID = Trim(ProvinceID)
	PostalCode = Trim(PostalCode)
	CreatedBy = Trim(CreatedBy)
	CompanyID = Trim(CompanyID)
	OriginationCoID = Trim(OriginationCoID)
	
	'Response.Write "OriginationCoID " & OriginationCoID & "<br><br>"
	'Response.Write "ProvinceID " & ProvinceID & "<br><br>"
	
	If bSubmitted <> "" Then
	
		  
		  If CompanyName = "" then 
	
				 strErrMsg = " Please enter a value for - CompanyName"
	
		  ElseIf Address1 = "" then 
	
				 strErrMsg = " Please enter a value for - Address1"
	
		  'ElseIf Address2 = "" then 
	
				 'strErrMsg = " Please enter a value for - Address2"
	
		  'ElseIf Address3 = "" then 
	
				 'strErrMsg = " Please enter a value for - Address3"
	
		  'ElseIf Address4 = "" then 
	
				 'strErrMsg = " Please enter a value for - Address4"
	
		  ElseIf City = "" then 
	
				 strErrMsg = " Please enter a value for - City"
	
		  ElseIf ProvinceID = "" then 
	
				 strErrMsg = " Please enter a value for - ProvinceID"
	
		  ElseIf PostalCode = "" then 
	
				 strErrMsg = " Please enter a value for - PostalCode"
	
		  ElseIf CreatedBy = "" then 
	
				 strErrMsg = " Please enter a value for - CreatedBy"
	
		  'ElseIf CompanyID = "" then 
	
				 'strErrMsg = " Please enter a value for - CompanyID"
	
		 ElseIf OriginationCoID = "" then 
	
				 strErrMsg = " Please enter a value for - OriginationCoID"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	
	
	<%
	
	
	If bSubmitted <> "" AND bFilledOutProperly Then
	
	Dim oConn
	
	Dim oCmd
	
	CompanyID = 0
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	
	With oCmd
	
		  .CommandText = "ins_Company"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						
						 .Parameters.Append .CreateParameter("@CompanyName",200, 1,100, CompanyName)
	
						 .Parameters.Append .CreateParameter("@Address1",200, 1,100, Address1)
	
						 .Parameters.Append .CreateParameter("@Address2",200, 1,100, Address2)
	
						 .Parameters.Append .CreateParameter("@Address3",200, 1,100, Address3)
	
						 .Parameters.Append .CreateParameter("@Address4",200, 1,100, Address4)
	
						 .Parameters.Append .CreateParameter("@City",200, 1,100, City)
	
						 .Parameters.Append .CreateParameter("@ProvinceID",3, 1,4, ProvinceID)
	
						 .Parameters.Append .CreateParameter("@PostalCode",200, 1,50, PostalCode)
	
						 .Parameters.Append .CreateParameter("@CreatedBy",3, 1,4, CreatedBy)
	
					' last param = 4 which is the value for an alias company
					.Parameters.Append .CreateParameter("@CompanyTypeID",3, 1,4, 4)
	
						 .Parameters.Append .CreateParameter("@OriginationCoID",3, 1,4, OriginationCoID)
		
					.Parameters.Append .CreateParameter("@CompanyID",3, 3,4, CLng(CompanyID))
	End With
	oConn.Open strDBaseConnString
	oCmd.ActiveConnection = oConn
	oCmd.Execute , , 128
	CompanyID = oCmd.Parameters("@CompanyID").value
	
	
	If oConn.Errors.Count < 1 then
	
		Response.Write "<BR><BR><STRONG>Alias company added successfully.</STRONG>"
		Response.End
	
	else
	
		  strErrMsg = Err.description
		  Err.Clear
	
	End If
	
	
	End If
	
	
	If strErrMsg <> "" Then
	
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	
	
	End If %>
	
	
	<form name="thisForm" id="thisForm" method="post" action="ins_companyalias.asp">
	
	<br><br>
	<STRONG>Alias Company Information</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	</td>
	<td>
	
	<input type="hidden" name="txtAliasCompany" id="txtAliasCompany" Value="<%=AliasCompany%>" >
	
	</td>
	</tr><tr>
	<td>
	
	*CompanyName
	
	</td>
	<td>
	
	<input type="text" name="txtCompanyName" id="txtCompanyName" MaxLength=100 Size=50 Value="<%=CompanyName%>" >
	
	</td>
	</tr><tr>
	<td>
	
	*Address1
	
	</td>
	<td>
	
	<input type="text" name="txtAddress1" id="txtAddress1" MaxLength=100 Size=50 Value="<%=Address1%>" >
	
	</td>
	</tr><tr>
	<td>
	
	Address2
	
	</td>
	<td>
	
	<input type="text" name="txtAddress2" id="txtAddress2" MaxLength=100 Size=50 Value="<%=Address2%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtAddress3" id="txtAddress3" MaxLength=100 Value="<%=Address3%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtAddress4" id="txtAddress4" MaxLength=100 Value="<%=Address4%>" >
	
	</td>
	</tr><tr>
	<td>
	
	*City
	
	</td>
	<td>
	
	<input type="text" name="txtCity" id="txtCity" MaxLength=100 Value="<%=City%>" >
	
	</td>
	</tr><tr>
	<td>
	*State
	
	</td>
	<td>
	
	
	<%
	
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	Set oRs = CreateObject("ADODB.Recordset")
	
	
	
	With oCmd
	
		  .CommandText = "sel_Province_all"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
	
	
	End With
	
	
	
	
	oConn.Open strDBaseConnString
	
	oCmd.ActiveConnection = oConn
	
	
	oRs.CursorLocation = 3
	
	oRs.Open oCmd, , 0, 1
	
	
	
	
	If oConn.Errors.Count < 1 then
	
		%>
		<select name="txtProvinceID">
	
		<%
		if bSubmitted = "" then
		
			while oRs.EOF = FALSE
			%>
				<option value="<%=oRs("ProvinceID")%>"><%=oRs("Prv_Name")%>
			<%
				oRs.MoveNext
		
			wend
		
		else
		
			while oRs.EOF = FALSE
			
				if CInt(oRs("ProvinceID")) = CInt(ProvinceID) then
				
			
				%>
					<option value="<%=oRs("ProvinceID")%>" selected><%=oRs("Prv_Name")%>
				<%
				else
			%>
					<option value="<%=oRs("ProvinceID")%>"><%=oRs("Prv_Name")%>
			<%
				end if
			
				oRs.MoveNext
		
			wend
		
		
		end if
	
	end if
	
	
	Set oConn = Nothing
	Set oCmd = Nothing
	Set oRs = Nothing
	
	
	%>
	
	</select>
	
	</td>
	</tr><tr>
	<td>
	
	*PostalCode
	
	</td>
	<td>
	
	<input type="text" name="txtPostalCode" id="txtPostalCode" MaxLength=5 Size=5 Value="<%=PostalCode%>" >
	
	</td>
	</tr>
	
	<tr>
	<td>
	
	*Associated Reseller
	
	</td>
	<td>
	
	
	<%
	
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	Set oRs = CreateObject("ADODB.Recordset")
	
	
	
	With oCmd
	
		  .CommandText = "sel_company_companytype"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
		  ' the last param = 3 which is the value for a reseller
		 .Parameters.Append .CreateParameter("@CompanyTypeID", 3, 1,4, 3)
	
	End With
	
	
	
	
	oConn.Open strDBaseConnString
	
	oCmd.ActiveConnection = oConn
	
	
	oRs.CursorLocation = 3
	
	oRs.Open oCmd, , 0, 1
	
	
	
	
	If oConn.Errors.Count < 1 then
	
		%>
		<select name="txtOriginationCoID">
	
		<%
		if bSubmitted = "" then
		
			%>
				<option value="0" selected>Not Related to a Reseller
			<%
			
		
			while oRs.EOF = FALSE
			%>
				<option value="<%=oRs("CompanyID")%>"><%=oRs("CompanyName")%>
			<%
				oRs.MoveNext
		
			wend
		
		else
			
			if OriginationCoID = 0 then
				%>
				<option value="0" selected>Not Related to a Reseller
				<%
			else
				%>
					<option value="0" >Not Related to a Reseller
				<%
			end if	
		
			while oRs.EOF = FALSE
			
				if CInt(oRs("CompanyID")) = CInt(OriginationCoID) and OriginationCoID <> 0 then
				
			
				%>
					<option value="<%=oRs("CompanyID")%>" selected><%=oRs("CompanyName")%>
				<%
				else
			%>
					<option value="<%=oRs("CompanyID")%>"><%=oRs("CompanyName")%>
			<%
				end if
			
				oRs.MoveNext
		
			wend
		
		
		end if
	
	end if
	
	
	Set oConn = Nothing
	Set oCmd = Nothing
	Set oRs = Nothing
	
	
	%>
	
	</select>
	
	</td>
	</tr>
	
	<tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtCreatedBy" id="txtCreatedBy" Value="<%=CreatedBy%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtCompanyID" id="txtCompanyID" Value="<%=CompanyID%>" >
	
	</td>
	</tr></table><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="submit" border=0 value="Add Alias Company" id=add name=add>
	
	</form>
	* - Required
	<br><br>
	While some items are required when matching a user's company to this alias company
	only the company name and it's additional aliases are considered.
	
	</body>
	
	</html>
	
</div>
</body>
</html>
