<%@ Language=VBScript %>
<!--#INCLUDE FILE="include/checklogin.asp" -->
<!--#INCLUDE FILE="include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="/pdi/_system.css" type="text/css"><!-- system stylesheet must come before the reseller stylesheet -->
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/reseller.css" type="text/css">
	<!--#INCLUDE FILE="include/head_stuff.asp" -->	
</head>
<body>
<!--#INCLUDE FILE="include/top_banner.asp" -->
<!--#INCLUDE FILE="include/left_navbar.asp" -->
<div id="maincontent">
	
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Tuesday, March 05, 2002  15:37:01
	'* Copyright (c) 2002 Team Resources, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure del_PricePlan_TRTest using ADO.
	'**********************************************************************************************************************************
	on error resume next
	
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim PricePlanID
	Dim TRTestID
	
	Dim TestName
	Dim PricePlanName
	
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
	
		  PricePlanID = Request.Form("txtPricePlanID")
	
		  TRTestID = Request.Form("txtTRTestID")
		  
		  TestName = Request.Form("txtTestName")
		  
		  PricePlanName = Request.Form("txtPricePlanName")
		  
	else
	
		PricePlanID = Request.QueryString("PPID")
		TRTestID = Request.QueryString("TID")
	
		TestName = Request.QueryString("TN")
		PricePlanName = Request.QueryString("PPN")
	
	End If
	
	PricePlanID = Trim(PricePlanID)
	TRTestID = Trim(TRTestID)
	
	
	If bSubmitted <> "" Then
	
		  If PricePlanID = "" then 
	
				 strErrMsg = " Please enter a value for - PricePlanID"
	
		  ElseIf TRTestID = "" then 
	
				 strErrMsg = " Please enter a value for - TRTestID"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	
	
	<%
	
	
	If bSubmitted <> "" AND bFilledOutProperly Then
	
	Dim oConn
	
	Dim oCmd
	
	
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	
	
	
	With oCmd
	
		  .CommandText = "del_PricePlan_TRTest"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
		  .Parameters.Append .CreateParameter("@PricePlanID",3, 1,4, PricePlanID)
	
		  .Parameters.Append .CreateParameter("@TRTestID",3, 1,4, TRTestID)
		 .Parameters.Append .CreateParameter("@ModifiedBy",3, 1,4, Request.Cookies("UserID"))
	
	End With
	
	oConn.Open strDBAseConnString
	
	oCmd.ActiveConnection = oConn
	
	
	oCmd.Execute , , 128
	
	
	
	
	If oConn.Errors.Count < 1 then
	
		Response.Redirect("editpriceplan.asp?PPID=" & PricePlanID)
	
	else
	
	
	
	
		  strErrMsg = Err.description
		  Err.Clear
	
	
	End If
	
	
	End If
	
	
	If strErrMsg <> "" Then
	
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	
	
	End If %>
	
	
	
	<br><br><STRONG>
	Price Plan Name: <%=PricePlanName%>
	<br><br>
	Test Name: <%=TestName%>
	<br><br>
	<form name="thisForm" id="thisForm" method="post" action="delcustomtestprice.asp">
	
	Remove Custom Test Price</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtPricePlanID" id="txtPricePlanID" Value="<%=PricePlanID%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtTRTestID" id="txtTRTestID" Value="<%=TRTestID%>" >
	
	<input type="hidden" name="txtTestName" id="txtTestName" value=<%=TEstName%>>
	<input type="hidden" name="txtPricePlanName" id="txtPricePlanName" value=<%=PricePlanName%>>
	
	</td>
	</tr></table>
	<br>
	Are you sure you want to remove this custom test price?
	<br><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="submit" border=0 value="Remove" id=add name=add>
	
	</form>
	
	
	</body>
	
	</html>
	
</div>
</body>
</html>
