<%@ Language=VBScript %>
<!--#INCLUDE FILE="include/CheckAdminLogin.asp" -->
<!--#INCLUDE FILE="../include/common.asp" -->
<% pageID = "home"
Dim Site
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="/pdi/_system.css" type="text/css"><!-- system stylesheet must come before the reseller stylesheet -->
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/reseller.css" type="text/css">
	<!--#INCLUDE FILE="../include/head_stuff.asp" -->	
</head>
<body>
	<!--#INCLUDE FILE="include/header.asp" -->
	<div class="TopNav">
	<a href="../main.asp?res=<%=intResellerID%>">PDI Home</a>&nbsp;|
	<a href="../logout.asp?res=<%=intResellerID%>">Logout</a>&nbsp;
</div>
	<div id="maincontent">
		
		<%
		'*****************************************************************************************
		'*
		'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
		'* Created By: David Brackin
		'* Creation Date: Saturday, March 02, 2002  12:53:58
		'* Copyright (c) 2002 Team Resources, Inc.
		'*
		'* ----  Code Settings ----
		'*
		'* Returns Recordset: YES
		'* Purpose: This ASP page calls the stored procedure sel_v_TestCode_Company_TestCode using ADO.
		'**********************************************************************************************************************************
		
		on error resume next
		
		Dim bSubmitted, ResellerID, PurchaserID, TestTakerID
		
		ResellerID = 0 
		PurchaserID = 0 
		TestTakerID = 0
		
		
		bSubmitted = Request.Form ("txtSubmit")
		
		Dim bFilledOutProperly, strErrMsg
		
		Dim TestCode
		
		
		bFilledOutProperly = FALSE
		
		If bSubmitted <> "" Then
		
		
			  TestCode = Request.Form("txtTestCode")
		
		
		
		End If
		
		TestCode = Trim(TestCode)
		
		
		If bSubmitted <> "" Then
		
			  If TestCode = "" then 
		
					 strErrMsg = " Please enter a value for - TestCode"
		
			  Else
		
					 bFilledOutProperly = TRUE
		
			  End If
		
		End If%>
		
		
		<br><br>
		<form name="thisForm" id="thisForm" method="post" action="viewtestcodeinfo.asp">
		
		<STRONG>Enter Profile Code</STRONG>
		
		<br><br>
		
		<table>
		
		<tr>
		<td>
		
		Profile Code
		
		</td>
		<td>
		
		<input type="text" name="txtTestCode" id="txtTestCode" MaxLength=50 Value="<%=TestCode%>" >
		
		</td>
		</tr></table><br>
		
		<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
		
		<input type="submit" border=0 value="Search" id=add name=add>
		
		</form>
		
		<%
		
		
		If bSubmitted <> "" AND bFilledOutProperly Then
		
			Dim oConn
			Dim oCmd
			Dim oRs
		
			Set oConn = CreateObject("ADODB.Connection")
			Set oCmd = CreateObject("ADODB.Command")
			Set oRs = CreateObject("ADODB.Recordset")
		
			With oCmd
		
				  .CommandText = "sel_TestCode_TestCode"
				  .CommandType = 4
		
				  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
					.Parameters.Append .CreateParameter("@TestCode",200, 1,50, TestCode)
		
			End With
		
			oConn.Open strDBaseConnString
		
			oCmd.ActiveConnection = oConn
		
			oRs.CursorLocation = 3
		
			oRs.Open oCmd, , 0, 1
		
			If oConn.Errors.Count < 1 then
		
				'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
				'Response.Write "<BR><BR>"
				'Response.Write "No. Of Records: " & oRs.RecordCount
				'Response.Write "<BR><BR>"
				
				
				Dim Field, nColumns
		
				If oRs.EOF = FALSE then
				
					Response.Write "<STRONG>Profile Code General Information</STRONG>"
					
					oRs.MoveFirst
					
					Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
					Response.Write "<TR>"
		
					Response.Write "<TD><font size=2><STRONG>Profile Code Creation Date</STRONG>"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2><STRONG>Purchased</STRONG>"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2><STRONG>Purchase Date</STRONG>"
					Response.Write "</TD>"
		
					Response.Write "<TD><font size=2><STRONG>Profile Code</STRONG>"
					Response.Write "</TD>"
		
					Response.Write "<TD><font size=2><STRONG>TRTestID</STRONG>"
					Response.Write "</TD>"
					
					Response.Write "</TR>"
		
					do while oRs.EOF = FALSE
		
						Response.Write "<TR>"
		
						Response.Write "<TD><font size=2>" & oRs("CreationDate")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>"
						
						if oRs("Purchased") = 1 then
							Response.Write "YES"
						else
							Response.Write "NO"
						end if
						
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" 
						
						if ISNULL(oRs("PurchaseDate")) = TRUE Then
							Response.Write "&nbsp;"
						else
							Response.Write oRs("PurchaseDate")
						end if
						Response.Write "</TD>"
		
		
						Response.Write "<TD><font size=2>" & oRs("TestCode")
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>" & oRs("TRTestID")
						Response.Write "</TD>"
						
						
						Response.Write "</TR>"
		
		
						oRs.MoveNext
		
					Loop
		
					Response.Write "</TABLE>"
		
				End If
		
				
		
			else
		
				  strErrMsg = Err.description
				  Err.Clear
		
			End If
		
		
		End If
		
		
		If strErrMsg <> "" Then
		
			  Response.Write "<br>"
			  Response.Write strErrMsg
			  Response.Write "<br><br>"
		
		
		End If 
		
		
		Set oConn = Nothing
		Set oCmd = Nothing
		Set oRs = Nothing
			
			
		If bSubmitted <> "" AND bFilledOutProperly Then
		
			
		
			Set oConn = CreateObject("ADODB.Connection")
			Set oCmd = CreateObject("ADODB.Command")
			Set oRs = CreateObject("ADODB.Recordset")
		
			With oCmd
		
				  .CommandText = "sel_v_TestCode_Purchase_TestCode"
				  .CommandType = 4
		
				  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
					.Parameters.Append .CreateParameter("@TestCode",200, 1,50, TestCode)
		
			End With
		
			oConn.Open strDBaseConnString
		
			oCmd.ActiveConnection = oConn
		
			oRs.CursorLocation = 3
		
			oRs.Open oCmd, , 0, 1
		
			If oConn.Errors.Count < 1 then
		
				'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
				'Response.Write "<BR><BR>"
				'Response.Write "No. Of Records: " & oRs.RecordCount
				Response.Write "<BR><BR>"
			
		
		
				If oRs.EOF = FALSE then
				
					Response.Write "<STRONG>Profile Code Purchase Information</STRONG>"
					
					oRs.MoveFirst
		
					Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
					Response.Write "<TR>"
		
					
					Response.Write "<TD><font size=2>Total Purchase Amount"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Total Purchase Discount"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Total Purchase Commission"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Total No. of Tests Purchased"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Test Price Paid"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Test Discount Amount"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Test Commission Amount"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Profile Code Redeemed?"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Redeem Date"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>PurchaseID"
					Response.Write "</TD>"
		
					Response.Write "<TD><font size=2>TestCodeID"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>TRTestID"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Test Purchaser ID"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Test Taker ID"
					Response.Write "</TD>"
								
					Response.Write "</TR>"
		
					do while oRs.EOF = FALSE
					
						PurchaserID = oRs("UserID")
						
						If IsNULL(oRs("TestTakerID")) = FALSE then
						
							TestTakerID = oRs("TestTakerID")
							
						End if
		
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("TotalAmount"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("TotalDiscount"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("TotalCommission"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("NoTestsPurchased")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("TestPrice"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("DiscountAmount"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & FormatCurrency(oRs("CommissionAmount"),2)
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" 
						
						if oRs("Redeemed") = 1 then 
							Response.Write "YES"
						else
							Response.Write "NO"
						end if
						
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" 
						if ISNULL(oRs("RedeemDate")) = TRUE then
							Response.Write "&nbsp;"
						else
							Response.Write oRs("RedeemDate")
						end if
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("PurchaseID")
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>" & oRs("TestCodeID")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("TRTestID")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("UserID")
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>" 
						if ISNULL(oRs("TestTakerID")) = TRUE then
							Response.Write "&nbsp;"
						else
							Response.Write oRs("TestTakerID")
						end if
						Response.Write "</TD>"
		
						oRs.MoveNext
		
					Loop
		
					Response.Write "</TABLE>"
		
				Else
				
					Response.Write "This profile code has not been purchased."
		
				End If
		
				
		
			else
		
				  strErrMsg = Err.description
				  Err.Clear
		
			End If
		
		
		End If
		
		
		If strErrMsg <> "" Then
		
			  Response.Write "<br>"
			  Response.Write strErrMsg
			  Response.Write "<br><br>"
		
		
		End If 
		
		if PurchaserID <> 0 then
		
			Set oConn = Nothing
			Set oCmd = Nothing
			Set oRs = Nothing
				
				
			Dim PurchaserCoID
			
			
			
			If bSubmitted <> "" AND bFilledOutProperly Then
		
				Set oConn = CreateObject("ADODB.Connection")
				Set oCmd = CreateObject("ADODB.Command")
				Set oRs = CreateObject("ADODB.Recordset")
		
				With oCmd
		
					  .CommandText = "sel_UserInfo_UserID"
					  .CommandType = 4
		
					  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						.Parameters.Append .CreateParameter("@UserID",3,1,4, PurchaserID)
		
				End With
		
				oConn.Open strDBaseConnString
		
				oCmd.ActiveConnection = oConn
		
				oRs.CursorLocation = 3
		
				oRs.Open oCmd, , 0, 1
		
				If oConn.Errors.Count < 1 then
		
					'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
					'Response.Write "<BR><BR>"
					'Response.Write "No. Of Records: " & oRs.RecordCount
					Response.Write "<BR><BR>"
				
		
		
					If oRs.EOF = FALSE then
					
						Response.Write "<STRONG>Profile Code Purchaser Information</STRONG>"
						
						oRs.MoveFirst
						
						
		
						Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
						Response.Write "<TR>"
		
						Response.Write "<TD><font size=2>User Name"
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>First Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Last Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Position"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Team Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Department"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Email Address"
						Response.Write "</TD>"
						
						Response.Write "</TR>"
		
						do while oRs.EOF = FALSE
		
							Response.Write "<TR>"
							
							PurchaserCoID = oRs("CompanyID")	
							
							Response.Write "<TD><font size=2>" & oRs("UserName")
							Response.Write "</TD>"
		
							Response.Write "<TD><font size=2>" & oRs("FirstName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("LastName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Postition")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("TeamName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Department")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("EmailAddress")
							Response.Write "</TD>"
						
										
							Response.Write "</TR>"
		
							oRs.MoveNext
		
						Loop
		
						Response.Write "</TABLE>"
		
					Else
					
						Response.Write "Purchaser information not found."
		
					End If
		
				else
		
					  strErrMsg = Err.description
					  Err.Clear
		
				End If
		
			End If
		
			Set oConn = Nothing
			Set oCmd = Nothing
			Set oRs = Nothing
				
				
			If bSubmitted <> "" AND bFilledOutProperly Then
		
				
		
				Set oConn = CreateObject("ADODB.Connection")
				Set oCmd = CreateObject("ADODB.Command")
				Set oRs = CreateObject("ADODB.Recordset")
		
				With oCmd
		
					  .CommandText = "sel_Company"
					  .CommandType = 4
		
					  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						.Parameters.Append .CreateParameter("@CompanyID",3, 1,4, PurchaserCoID)
		
				End With
		
				oConn.Open strDBaseConnString
		
				oCmd.ActiveConnection = oConn
		
				oRs.CursorLocation = 3
		
				oRs.Open oCmd, , 0, 1
		
				If oConn.Errors.Count < 1 then
		
					'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
					'Response.Write "<BR><BR>"
					'Response.Write "No. Of Records: " & oRs.RecordCount
					Response.Write "<BR><BR>"
				
		
		
					If oRs.EOF = FALSE then
					
						Response.Write "<STRONG>Profile Code Purchaser Company Information</STRONG>"
						
						oRs.MoveFirst
		
						Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
						Response.Write "<TR>"
		
						
						Response.Write "<TD><font size=2>Company Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Address1"
						Response.Write "</TD>"
									
						Response.Write "<TD><font size=2>"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>City"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Postal Code"
						Response.Write "</TD>"
										
						
						Response.Write "</TR>"
		
						do while oRs.EOF = FALSE
		
							
							Response.Write "<TD><font size=2>" & oRs("CompanyName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Address1")
							Response.Write "</TD>"
										
							Response.Write "<TD><font size=2>" & oRs("City")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("PostalCode")
							Response.Write "</TD>"
							
							
							oRs.MoveNext
		
						Loop
		
						Response.Write "</TABLE>"
		
					Else
					
						Response.Write "<br> The purchaser is not related to a company.<br>"
		
					End If
		
					
		
				else
		
					  strErrMsg = Err.description
					  Err.Clear
		
				End If
		
		
			End If
		
		
			If strErrMsg <> "" Then
		
				  Response.Write "<br>"
				  Response.Write strErrMsg
				  Response.Write "<br><br>"
		
		
			End If 
		
		
		End if
		
		
		Dim TestTakerCoID
		
		
		
		if TestTakerID <> 0 then
		
			Set oConn = Nothing
			Set oCmd = Nothing
			Set oRs = Nothing
				
				
				
			
			
			If bSubmitted <> "" AND bFilledOutProperly Then
		
				Set oConn = CreateObject("ADODB.Connection")
				Set oCmd = CreateObject("ADODB.Command")
				Set oRs = CreateObject("ADODB.Recordset")
		
				With oCmd
		
					  .CommandText = "sel_UserInfo_UserID"
					  .CommandType = 4
		
					  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						.Parameters.Append .CreateParameter("@UserID",3,1,4, TestTakerID)
		
				End With
		
				oConn.Open strDBaseConnString
		
				oCmd.ActiveConnection = oConn
		
				oRs.CursorLocation = 3
		
				oRs.Open oCmd, , 0, 1
		
				If oConn.Errors.Count < 1 then
		
					'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
					'Response.Write "<BR><BR>"
					'Response.Write "No. Of Records: " & oRs.RecordCount
					Response.Write "<BR><BR>"
				
		
		
					If oRs.EOF = FALSE then
					
						Response.Write "<STRONG>Profile Code - Test Taker Information</STRONG>"
						
						oRs.MoveFirst
		
						Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
						Response.Write "<TR>"
		
						Response.Write "<TD><font size=2>User Name"
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>First Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Last Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Position"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Team Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Department"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Email Address"
						Response.Write "</TD>"
						
						Response.Write "</TR>"
		
						do while oRs.EOF = FALSE
		
							Response.Write "<TR>"
		
							Response.Write "<TD><font size=2>" & oRs("UserName")
							Response.Write "</TD>"
		
							Response.Write "<TD><font size=2>" & oRs("FirstName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("LastName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Postition")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("TeamName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Department")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("EmailAddress")
							Response.Write "</TD>"
							
							TestTakerCoID = oRs("CompanyID")
						
										
							Response.Write "</TR>"
		
							oRs.MoveNext
		
						Loop
		
						Response.Write "</TABLE>"
		
					Else
					
						Response.Write "This profile code is not related to test taker."
		
					End If
		
				else
		
					  strErrMsg = Err.description
					  Err.Clear
		
				End If
		
			End If
		
		
		
		If bSubmitted <> "" AND bFilledOutProperly Then
		
				
		
				Set oConn = CreateObject("ADODB.Connection")
				Set oCmd = CreateObject("ADODB.Command")
				Set oRs = CreateObject("ADODB.Recordset")
		
				With oCmd
		
					  .CommandText = "sel_Company"
					  .CommandType = 4
		
					  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						.Parameters.Append .CreateParameter("@CompanyID",3, 1,4, TestTakerCoID)
		
				End With
		
				oConn.Open strDBaseConnString
		
				oCmd.ActiveConnection = oConn
		
				oRs.CursorLocation = 3
		
				oRs.Open oCmd, , 0, 1
		
				If oConn.Errors.Count < 1 then
		
					'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
					'Response.Write "<BR><BR>"
					'Response.Write "No. Of Records: " & oRs.RecordCount
					Response.Write "<BR><BR>"
				
		
		
					If oRs.EOF = FALSE then
					
						Response.Write "<STRONG>Profile Code - Test Taker Company Information</STRONG>"
						
						oRs.MoveFirst
		
						Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
						Response.Write "<TR>"
		
						
						Response.Write "<TD><font size=2>Company Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Address1"
						Response.Write "</TD>"
									
						Response.Write "<TD><font size=2>"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>City"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Postal Code"
						Response.Write "</TD>"
										
						
						Response.Write "</TR>"
		
						do while oRs.EOF = FALSE
		
							
							Response.Write "<TD><font size=2>" & oRs("CompanyName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Address1")
							Response.Write "</TD>"
										
							Response.Write "<TD><font size=2>" & oRs("City")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("PostalCode")
							Response.Write "</TD>"
							
							
							oRs.MoveNext
		
						Loop
		
						Response.Write "</TABLE>"
		
					Else
					
						Response.Write "<br> The test taker is not related to a company.<br>"
		
					End If
		
					
		
				else
		
					  strErrMsg = Err.description
					  Err.Clear
		
				End If
		
		
			End If
		
		
			If strErrMsg <> "" Then
		
				  Response.Write "<br>"
				  Response.Write strErrMsg
				  Response.Write "<br><br>"
		
		
			End If 
			
		End if
		
		
		Set oConn = Nothing
		Set oCmd = Nothing
		Set oRs = Nothing
			
			
		If bSubmitted <> "" AND bFilledOutProperly Then
		
			
		
			Set oConn = CreateObject("ADODB.Connection")
			Set oCmd = CreateObject("ADODB.Command")
			Set oRs = CreateObject("ADODB.Recordset")
		
			With oCmd
		
				  .CommandText = "sel_v_TestCode_Company_TestCode"
				  .CommandType = 4
		
				  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
					.Parameters.Append .CreateParameter("@TestCode",200, 1,50, TestCode)
		
			End With
		
			oConn.Open strDBaseConnString
		
			oCmd.ActiveConnection = oConn
		
			oRs.CursorLocation = 3
		
			oRs.Open oCmd, , 0, 1
		
			If oConn.Errors.Count < 1 then
		
				'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
				'Response.Write "<BR><BR>"
				'Response.Write "No. Of Records: " & oRs.RecordCount
				Response.Write "<BR><BR>"
			
		
		
				If oRs.EOF = FALSE then
				
					Response.Write "<STRONG>Profile Code Company Relation Information</STRONG>"
					
					oRs.MoveFirst
		
					Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
					Response.Write "<TR>"
		
					Response.Write "<TD><font size=2>CompanyName"
					Response.Write "</TD>"
		
					Response.Write "<TD><font size=2>Address1"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>City"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>PostalCode"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Company Relation Date"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Related to Company By Reseller"
					Response.Write "</TD>"
					
					Response.Write "<TD><font size=2>Related Company ID"
					Response.Write "</TD>"
					
					Response.Write "</TR>"
		
					do while oRs.EOF = FALSE
		
						Response.Write "<TR>"
		
						Response.Write "<TD><font size=2>" & oRs("CompanyName")
						Response.Write "</TD>"
		
						Response.Write "<TD><font size=2>" & oRs("Address1")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("City")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("PostalCode")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" & oRs("CompanyRelDate")
						Response.Write "</TD>"
					
						Response.Write "<TD><font size=2>" 
						
'						if ISNULL(oRs("OriginationID")) = TRUE then
'							Response.Write "NO"
'						else
'							Response.Write "YES"
'							ResellerID = oRs("OriginationID")
'						end if
						
						Response.Write "<TD><font size=2>" & oRs("CompanyID")
						Response.Write "</TD>"
						
						Response.Write "</TD>"
					
						Response.Write "</TR>"
		
						oRs.MoveNext
		
					Loop
		
					Response.Write "</TABLE>"
		
				Else
				
					Response.Write "This profile code is not related to a company."
		
				End If
		
				
		
			else
		
				  strErrMsg = Err.description
				  Err.Clear
		
			End If
		
		
		End If
		
		
		If strErrMsg <> "" Then
		
			  Response.Write "<br>"
			  Response.Write strErrMsg
			  Response.Write "<br><br>"
		
		
		End If 
		
		
		if ResellerID <> 0 then
		
			
		
			Set oConn = Nothing
			Set oCmd = Nothing
			Set oRs = Nothing
				
		
			 
			If bSubmitted <> "" AND bFilledOutProperly Then
		
				
		
				Set oConn = CreateObject("ADODB.Connection")
				Set oCmd = CreateObject("ADODB.Command")
				Set oRs = CreateObject("ADODB.Recordset")
		
				With oCmd
		
					  .CommandText = "sel_Company"
					  .CommandType = 4
		
					  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						.Parameters.Append .CreateParameter("@TestCode",3, 1,4, ResellerID)
		
				End With
		
				oConn.Open strDBaseConnString
		
				oCmd.ActiveConnection = oConn
		
				oRs.CursorLocation = 3
		
				oRs.Open oCmd, , 0, 1
		
				If oConn.Errors.Count < 1 then
		
					'Response.Write "<BR><BR>Transaction Successful<BR><BR>"
		
					'Response.Write "<BR><BR>"
					'Response.Write "No. Of Records: " & oRs.RecordCount
					Response.Write "<BR><BR>"
				
		
		
					If oRs.EOF = FALSE then
					
						Response.Write "<STRONG>Reseller Information</STRONG>"
						
						oRs.MoveFirst
		
						Response.Write "<TABLE BORDER=1 CELLPADDING=2 CELLSPACING=2 >"
		
						Response.Write "<TR>"
		
						
						Response.Write "<TD><font size=2>Company Name"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Address1"
						Response.Write "</TD>"
									
						Response.Write "<TD><font size=2>"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>City"
						Response.Write "</TD>"
						
						Response.Write "<TD><font size=2>Postal Code"
						Response.Write "</TD>"
										
						Response.Write "</TR>"
		
						do while oRs.EOF = FALSE
		
							
							Response.Write "<TD><font size=2>" & oRs("CompanyName")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("Address1")
							Response.Write "</TD>"
										
							Response.Write "<TD><font size=2>" & oRs("City")
							Response.Write "</TD>"
						
							Response.Write "<TD><font size=2>" & oRs("PostalCode")
							Response.Write "</TD>"
								
		
							oRs.MoveNext
		
						Loop
		
						Response.Write "</TABLE>"
		
					Else
					
						Response.Write "This profile code has not been purchased."
		
					End If
		
					
		
				else
		
					  strErrMsg = Err.description
					  Err.Clear
		
				End If
		
		
			End If
		
		
			If strErrMsg <> "" Then
		
				  Response.Write "<br>"
				  Response.Write strErrMsg
				  Response.Write "<br><br>"
		
		
			End If 
		
		end if
		
		%>
		</body>
		
		</html>
		
	</div>
</body>
</html>
