<div id="syn-header">
<table cellspacing="0" cellpadding="0" border="0" width="750">
	<tbody>
	    <tr>
		    <td background="rs/synovus/topbar.gif" align="right" colspan="2">
			<!-- div style="float:right">
				<img src="rs/synovus/focus3_logo.jpg" />
			</div -->
		    </td>
	    </tr>
	    <tr bgcolor="#cc0000">
		    <td><a href="http://www.synovus.com/index.cfm"><img hspace="16" height="43" border="0" width="132" alt="Synovus" src="rs/synovus/logo.gif"></a></td>
		    <td align="right">
			    &nbsp;
		    </td>
	    </tr>
    	
	    <tr height="26">
		    <td background="rs/synovus/navbar.gif" align="center" colspan="2">
			    <table cellspacing="0" cellpadding="0" border="0">
    				
					    <tbody><tr>
						    <td class="page-title"><!-- Personal DISC Assessment --></td>
					    </tr>
    				
			    </tbody></table>
		    </td>
	    </tr>
    </tbody>
</table>
</div>