<table class="page-header" cellSpacing="0" cellPadding="0" width="100%" border="0" ID="Table2">
	<tr>
		<td vAlign="bottom" align="left" width="20%"><img src="../images/logo.gif"></td>
		<td width="60%" align="center"><span class="banner-text">Personal&nbsp;DISCernment&nbsp;Inventory</span></td>
		<td width="20%">&nbsp;</td>
	</tr>
</table>
<table style="MARGIN-TOP: 1px" cellSpacing="0" cellPadding="0" width="100%" border="0"
	ID="Table3">
	<tr>
		<td class="tab-active-footer" vAlign="middle" align="right" colSpan="4">
			&nbsp;
		</td>
	</tr>
</table>
<br>
<div style="float:left"><img src="rs/pawowik/paragon_logo.gif" /></div>