<table align="center" width="756px" border="0" ID="content">
<tr><td>&nbsp;</td></tr>
<tr><td align="center"><h1>Welcome to the DISC Assessment</h1>
</td></tr>
<tr><td align="center" style="padding-left:100px;padding-right:100px">
<p>DISC is an excellent tool to help people understand themselves and others. It is not a test. There are no right or wrong answers. You cannot pass or fail. It merely gives insight into your work style and helps you work more effectively with others.  </p>

<p>You will be given 24 sets of four words each. For each of those four sets of words you are to choose one word that describes you MOST in the work setting. Of the remaining three words, choose the one word that describes you LEAST in the work setting. </p>

<p>Go with your first impression-don't over think and get introspective. With this type of assessment, first impressions generally prove to be the most accurate.</p>
</td></tr>
</table>
<table align="center" width="756px" style="background-color:#ffffff;" height="68%"><tr><td>&nbsp;</td></tr></table>