 <div id="header">
        <div id="banner-top">
            <div id="home-img"><img src="rs/thermodisc/EmersonHome.gif" alt="Emerson Home" /></div>
            <div id="logo"><img src="rs/thermodisc/EmersonSolutions.gif" alt="Emerson Solutions" /></div>
        </div>
        <div id="banner-middle">
            <div id="logo-thermodisc"><img src="rs/thermodisc/Logo.gif" alt="THERM-O-DISC" /></div>
            <div id="blue-area"><br />DISC Assessment&nbsp;</div>
            <div id="building-image"><img src="rs/thermodisc/Picture.gif" alt="THERM-O-DISC Building" /></div>
        </div>
        <div id="banner-bottom">
            &nbsp;
        </div>
    </div>