					</td></tr>
					<tr><td colspan="4"><img height="23px" alt="" src="http://www.starbucks.com/images/spacer.gif" width="1"></td></tr>
				</table>
      
				<div id="Footer" name="Footer" class="divFooter">
					<div id="CopyrightText" name="CopyrightText" class="divCopyright">
						&copy; 2007 Triaxia Partners. All rights reserved.
					</div>
					<div id="FooterLinks" name="FooterLinks" class="divFooterLinks">
						&nbsp;
					</div>
				</div>	
			</div>
		</div>
	</div>
</div>