<div id="WindowDiv" name="WindowDiv">
		<div id="PageDiv" name="PageDiv">
			<div class="pageLeft" id="PageLeft" name="PageLeft">
				<div><a href="http://www.starbucks.com/default.asp"><img alt="" 
							src="rs/starbucks/logo_top.gif" border=0></a>
				</div>
			</div>
			<div class="pageCenter" id="PageCenter" name="PageCenter">
				<div class="divHeader" id="Header" name="Header">
					<div class="divUtilityNav" id="UtilityNav" name="UtilityNav" style="position:relative;left:50px;height:85px;text-align:left;float:left;">
					Starbucks DISC Assessment
					</div>
				</div>
   
				<table width="100%" cellpadding="0" cellspacing="0">
				 <tr><td colspan="4"><img height="23px" alt="" src="http://www.starbucks.com/images/spacer.gif" width="1"></td></tr>
				 <tr><td>