<%=AppModParaFont%>
<%=UserName%>, aspects of your behavioral style may prove a help or hindrance as you work in 
sales. Below are listed the strengths and weaknesses commonly found in a high 
<%=HighType1%> temperament. They are organized around the key components of sales. 
Personalize this list by checking those items you believe accurately describe you and 
adding other items that come to mind as you review the list.
<%=EndAppModParaFont%>

<%=AppModParaFont%>
<TABLE WIDTH=70% BORDER=1 CELLSPACING=1 CELLPADDING=1>
	<TR>
		<TD>&nbsp;</TD>
		<TD ALIGN=MIDDLE><font size=3><STRONG>The High I Salesperson's Strengths</STRONG></TD>
		<TD ALIGN=MIDDLE><font size=3><STRONG>The High I Salesperson's Weaknesses</STRONG></TD>
	</TR>
	<TR>
		<TD><font size=3><STRONG>Targeting</STRONG></TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Prefers established clients in friendly 
environment</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>Responds well to leads generated by 
others</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
		
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Hesitant to contact strangers</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>May depend on others to generate leads</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
	</TR>
	<TR>
		<TD><font size=3><STRONG>Preparation</STRONG></TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Mentions mutual friends</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>Listens to others' ideas and feelings</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>Creates informal, non-threatening 
atmosphere</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>May be lackluster</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>May fail to ask penetrating questions</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>May not read buyer's situation well</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>May take too long to get down to business</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
	</TR>
	<TR>
		<TD><font size=3><STRONG>Presentation</STRONG></TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Low key and non-threatening</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>Wins buyer admiration and approval</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>Impresses buyer by personal example</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>Acts as buyer's advocate</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2></TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2></TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>Patient, with good listening skills</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>Deals with objections thoroughly and 
systematically</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>Examines each point in terms of buyer's 
best interest</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>May lack flexibility</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>May be well-organized but lacking in 
enthusiasm</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>Tends to be more explanatory than 
emotional</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>May get sidetracked</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>May not be forceful and may not push with 
conviction</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
	</TR>
	<TR>
		<TD><font size=3><STRONG>Commitment</STRONG></TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Doesn't push or rush buyer</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Tends to stay with the tried and true</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>May be too indirect and not push for a close</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
	</TR>
	<TR>
		<TD><font size=3><STRONG>Partnering</STRONG></TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>Gives excellent service</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>Provides systematic follow-up</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>Keeps accurate records</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2><font size=2>____________________________</TD>
				</TR>
				
			</TABLE>
	
		</TD>
		<TD VALIGN=TOP>
		
			<TABLE WIDTH=75% BORDER=0 CELLSPACING=1 CELLPADDING=1>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox1 name=checkbox1></TD>
					<TD><font size=2>May give too much service</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox2 name=checkbox2></TD>
					<TD><font size=2>May neglect customers who require his/her 
being away from home overnight</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox3 name=checkbox3></TD>
					<TD><font size=2>May spend too much time on paperwork</TD>
				</TR>
				<TR>
					<TD><font size=2><input type=checkbox id=checkbox4 name=checkbox4></TD>
					<TD><font size=2>Paperwork output will be accurate but not 
particularly creative</TD>
				</TR>
				<TR>
					<TD><input type=checkbox id=checkbox5 name=checkbox5></TD>
					<TD><font size=2>____________________________</TD>
				</TR>
			</TABLE>
	
		</TD>
	</TR>
</TABLE>
<%=EndAppModParaFont%>






