<p>
<% strTemp = Replace(strTextAspectsOfYourBehavioralStyleMa, "{{HighType1}}", HighType1) %>
<%=UserName%>, <%= strTemp %><!--aspects of your behavioral style may prove a help or hindrance as you work in sales. Below are listed the strengths and weaknesses commonly found in a high <%=HighType1%> temperament. They are organized around the key components of sales. Personalize this list by checking those items you believe accurately describe you and adding other items that come to mind as you review the list.-->
</p>


<TABLE WIDTH=100% BORDER=0 CELLSPACING=0 CELLPADDING=3>
	<TR>
		<TD style="border-top: 1px black solid; border-bottom: 1px black solid;">&nbsp;</TD>
		<TD style="border-top: 1px black solid; border-bottom: 1px black solid;" ALIGN=MIDDLE><font size=3><STRONG><%= strTextTheHighSSalespersonsStrengths %><!--The High S Salesperson's Strengths--></STRONG></TD>
		<TD style="border-top: 1px black solid; border-bottom: 1px black solid;" ALIGN=MIDDLE><font size=3><STRONG><%= strTextTheHighSSalespersonsWeaknesses %><!--The High S Salesperson's Weaknesses--></STRONG></TD>
	</TR>
	<TR>
		<TD style="border-bottom: 1px black solid;"><font size=3><STRONG><%= strTextTargeting %><!--Targeting--></STRONG></TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextPrefersEstablishedClientsInFri %><!--Prefers established clients in friendly environment--></li>
					<li><%= strTextRespondsWellToLeadsGeneratedBy %><!--Responds well to leads generated by others--></li>
					
			</ul>
		</TD>
		
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextHesitantToContactStrangers %><!--Hesitant to contact strangers--></li>
					<li><%= strTextMayDependOnOthersToGenerateLea %><!--May depend on others to generate leads--></li>
					
			</ul>
		</TD>
	</TR>
	<TR>
		<TD style="border-bottom: 1px black solid;"><font size=3><STRONG><%= strTextPreparation %><!--Preparation--></STRONG></TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextMentionsMutualFriends %><!--Mentions mutual friends--></li>
					<li><%= strTextListensToOthersIdeasAndFeeling %><!--Listens to others' ideas and feelings--></li>
					<li><%= strTextCreatesInformalNonthreateningA %><!--Creates informal, non-threatening atmosphere--></li>
					
			</ul>
		</TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextMayBeLackluster %><!--May be lackluster--></li>
					<li><%= strTextMayFailToAskPenetratingQuestio %><!--May fail to ask penetrating questions--></li>
					<li><%= strTextMayNotReadBuyersSituationWell %><!--May not read buyer's situation well--></li>
					<li><%= strTextMayTakeTooLongToGetDownToBusin %><!--May take too long to get down to business--></li>
					
			</ul>
		</TD>
	</TR>
	<TR>
		<TD style="border-bottom: 1px black solid;"><font size=3><STRONG><%= strTextPresentation %><!--Presentation--></STRONG></TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextLowKeyAndNonthreatening %><!--Low key and non-threatening--></li>
					<li><%= strTextWinsBuyerAdmirationAndApproval %><!--Wins buyer admiration and approval--></li>
					<li><%= strTextImpressesBuyerByPersonalExampl %><!--Impresses buyer by personal example--></li>
					<li><%= strTextActsAsBuyersAdvocate %><!--Acts as buyer's advocate--></li>
					<li><%= strTextPatientWithGoodListeningSkills %><!--Patient, with good listening skills--></li>
					<li><%= strTextDealsWithObjectionsThoroughlyA %><!--Deals with objections thoroughly and systematically--></li>
					<li><%= strTextExaminesEachPointInTermsOfBuye %><!--Examines each point in terms of buyer's best interest--></li>
					
			</ul>
		</TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextMayLackFlexibility %><!--May lack flexibility--></li>
					<li><%= strTextMayBeWellorganizedButLackingIn %><!--May be well-organized but lacking in enthusiasm--></li>
					<li><%= strTextTendsToBeMoreExplanatoryThanEm %><!--Tends to be more explanatory than emotional--></li>
					<li><%= strTextMayGetSidetracked %><!--May get sidetracked--></li>
					<li><%= strTextMayNotBeForcefulAndMayNotPushW %><!--May not be forceful and may not push with conviction--></li>
					
			</ul>
		</TD>
	</TR>
<!--
 old page and table break
-->
	<TR>
		<TD style="border-bottom: 1px black solid;"><font size=3><STRONG><%= strTextCommitment %><!--Commitment--></STRONG></TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextDoesntPushOrRushBuyer %><!--Doesn't push or rush buyer--></li>
					
			</ul>
		</TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextTendsToStayWithTheTriedAndTrue %><!--Tends to stay with the tried and true--></li>
					<li><%= strTextMayBeTooIndirectAndNotPushForA %><!--May be too indirect and not push for a close--></li>
					
			</ul>
		</TD>
	</TR>
	<TR>
		<TD style="border-bottom: 1px black solid;"><font size=3><STRONG><%= strTextPartnering %><!--Partnering--></STRONG></TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextGivesExcellentService %><!--Gives excellent service--></li>
					<li><%= strTextProvidesSystematicFollowup %><!--Provides systematic follow-up--></li>
					<li><%= strTextKeepsAccurateRecords %><!--Keeps accurate records--></li>
					
			</ul>
		</TD>
		<TD style="border-bottom: 1px black solid;" VALIGN=TOP>
			<ul class="checkbox">
					<li><%= strTextMayGiveTooMuchService %><!--May give too much service--></li>
					<li><%= strTextMayNeglectCustomersWhoRequireH %><!--May neglect customers who require his/her being away from home overnight--></li>
					<li><%= strTextMaySpendTooMuchTimeOnPaperwork %><!--May spend too much time on paperwork--></li>
					<li><%= strTextPaperworkOutputWillBeAccurateB %><!--Paperwork output will be accurate but not particularly creative--></li>
					
			</ul>
		</TD>
	</TR>
</TABLE>







