<link rel="stylesheet" type="text/css" href="rs/rtsamkeep/rtstyle.css">
<table cellpadding=0 cellspacing=0 border=0 width=776 align=center>
	<tr>
		<td width=36><a href="http://www.racetrac.com"><img src="rs/rtsamkeep/rtlogo.gif" border=0></a></td>
		<td width=740>
		<table cellpadding=0 cellspacing=0 border=0 align=center width=740 valign=top>
			<tr>
				<td valign=top>
				<table cellpadding=0 cellspacing=0 border=0 align=center width=900>
					<tr>
						<td class=TDheaderGRAYshadedBG5 colspan=3 height=36>&nbsp;&nbsp;&nbsp;&nbsp;Personal DISCernment Inventory</td>
					</tr>
					
				</table>
				</td>
			</tr>
			<tr>
				<td colspan=2>
				<table cellpadding=0 cellspacing=0 border=0 width=946>
					
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
</table>