<TABLE id="tblBanner" cellSpacing="0" cellPadding="0" border="0" align="center">
			<TR>
				<TD height="173" width="187"><IMG alt="" src="rs/abundantspeaking/ABC_Logo.GIF"></TD>
				<TD background="rs/abundantspeaking/Teal_White_TwoTone.GIF" width="569px" height="173px" vAlign="top" align="left">&nbsp;<BR>
					<span style="FONT-WEIGHT:bold; FONT-SIZE:18pt; COLOR:#ffffff; FONT-FAMILY:Tahoma">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Abundant Speaking</span></TD>
				<TD width="3"></TD>
			</TR>
		</TABLE>