<table border="0" cellpadding="0" cellspacing="0" align="center">
<tr><td><font face="Arial, Arial, Helvetica">
<p align="left">&nbsp;<img border="0" src="rs/lmac/LMALogo.jpg" width="269" height="133">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<img border="0" src="rs/lmac/Collage6a.jpg" width="228" height="154">
 </p>

</table>