<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Tuesday, March 05, 2002  15:16:56
	'* Copyright (c) 2002 Team Resources, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure upd_PricePlan_TRTest using ADO.
	'**********************************************************************************************************************************
	
	
	on error resume next
	
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim CustomPrice
	Dim LastModifiedBy
	Dim PricePlanID
	Dim TRTestID
	Dim TestName
	Dim PricePlanName
	
	
	
	
	
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
	
		  CustomPrice = Request.Form("txtCustomPrice")
	
		  LastModifiedBy = Request.Cookies("UserID")
	
		  PricePlanID = Request.Form("txtPricePlanID")
	
		  TRTestID = Request.Form("txtTRTestID")
		  
		  TestName = Request.Form("txtTestName")
		  
		  PricePlanName = Request.Form("txtPricePlanName")
	
	else
	
		PricePlanID = Request.QueryString("PPID")
		TRTestID = Request.QueryString("TID")
		
		TestName = Request.QueryString("TN")
		PricePlanName = Request.QueryString("PPN")
	
	End If
	
	CustomPrice = Trim(CustomPrice)
	LastModifiedBy = Trim(LastModifiedBy)
	PricePlanID = Trim(PricePlanID)
	TRTestID = Trim(TRTestID)
	TestName = TRIM(TestName)
	PricePlanName = TRIM(PricePlanName)
	
	
	If bSubmitted <> "" Then
	
		  If CustomPrice = "" then 
	
				 strErrMsg = " Please enter a value for - CustomPrice"
	
		  ElseIf LastModifiedBy = "" then 
	
				 strErrMsg = " Please enter a value for - LastModifiedBy"
	
		  ElseIf PricePlanID = "" then 
	
				 strErrMsg = " Please enter a value for - PricePlanID"
	
		  ElseIf TRTestID = "" then 
	
				 strErrMsg = " Please enter a value for - TRTestID"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	
	
	<%
	
	
	If bSubmitted <> "" AND bFilledOutProperly Then
	
	Dim oConn
	
	Dim oCmd
	
	
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	
	'Response.write "Price Plan ID = " & PRicePlanID & "<br>"
	'Response.write "TR Test ID = " & TRTestID & "<br>"
	
	'Response.End
	
	With oCmd
	
		  .CommandText = "upd_PricePlan_TRTest"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						 .Parameters.Append .CreateParameter("@CustomPrice",6, 1,21, CustomPrice)
	
						 .Parameters.Append .CreateParameter("@LastModifiedBy",3, 1,4, LastModifiedBy)
	
						 .Parameters.Append .CreateParameter("@PricePlanID",3, 1,4, PricePlanID)
	
						 .Parameters.Append .CreateParameter("@TRTestID",3, 1,4, TRTestID)
	
	
	
	End With
	
	
	
	
	oConn.Open strDbConnString
	
	oCmd.ActiveConnection = oConn
	
	
	oCmd.Execute , , 128
	
		If oConn.Errors.Count < 1 then
	
			Response.Redirect("editpriceplan.asp?PPID=" & PricePlanID)
	
		else
	
			 strErrMsg = Err.description
			 Err.Clear
	
		End If
	
	
	End If
	
	
	If strErrMsg <> "" Then
	
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	
	
	End If %>
	
	
	<br><br><STRONG>
	Price Plan Name: <%=PricePlanName%>
	<br><br>
	Test Name: <%=TestName%>
	<br><br>
	<form name="thisForm" id="thisForm" method="post" action="editcustomtestprice.asp">
	
	Update Custom Test Price</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	CustomPrice
	
	</td>
	<td>
	
	<input type="text" name="txtCustomPrice" id="txtCustomPrice" Value="<%=CustomPrice%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtLastModifiedBy" id="txtLastModifiedBy" Value="<%=LastModifiedBy%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtPricePlanID" id="txtPricePlanID" Value="<%=PricePlanID%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtTRTestID" id="txtTRTestID" Value="<%=TRTestID%>" >
	
	</td>
	</tr></table><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="hidden" name="txtTestName" id="txtTestName" value=<%=TEstName%>>
	<input type="hidden" name="txtPricePlanName" id="txtPricePlanName" value=<%=PricePlanName%>>
	
	<input type="submit" border=0 value="Update" id=add name=add>
	
	</form>
	
	
	</body>
	
	</html>
	
</div>
</body>
</html>
