<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Saturday, January 12, 2002  20:08:41
	'* Copyright (c) 2002 VoyageSoft, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure ins_PricePlan using ADO.
	'**********************************************************************************************************************************
	
	on error resume next
	
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim PricePlanName
	Dim Description
	Dim CreatedBy
	Dim Active
	
	
	
	
	CreatedBy = Request.Cookies("UserID")
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
	
		  PricePlanName = Request.Form("txtPricePlanName")
	
		  Description = Request.Form("txtDescription")
	
		  CreatedBy = Request.Form("txtCreatedBy")
	
		  Active = Request.Form("txtActive")
	
		 Active = 1 
		
	End If
	
	PricePlanName = Trim(PricePlanName)
	Description = Trim(Description)
	CreatedBy = Trim(CreatedBy)
	Active = Trim(Active)
	
	
	If bSubmitted <> "" Then
	
		  If PricePlanName = "" then 
	
				 strErrMsg = " Please enter a value for - PricePlanName"
	
		  ElseIf Description = "" then 
	
				 strErrMsg = " Please enter a value for - Description"
	
		  ElseIf CreatedBy = "" then 
	
				 strErrMsg = " Please enter a value for - CreatedBy"
	
		  ElseIf Active = "" then 
	
				 strErrMsg = " Please enter a value for - Active"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	
	
	<%
	
	
	If bSubmitted <> "" AND bFilledOutProperly Then
	
	Dim oConn
	
	Dim oCmd
	
	
	
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	
	
	
	With oCmd
	
		  .CommandText = "ins_PricePlan"
		  .CommandType = 4
	
	
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
						 .Parameters.Append .CreateParameter("@PricePlanName",200, 1,20, PricePlanName)
	
						 .Parameters.Append .CreateParameter("@Description",200, 1,100, Description)
	
						 .Parameters.Append .CreateParameter("@CreatedBy",3, 1,4, CreatedBy)
	
						 .Parameters.Append .CreateParameter("@Active",3, 1,4, Active)
	
	
	
	End With
	
	
	
	
	oConn.Open strDbConnString
	
	oCmd.ActiveConnection = oConn
	
	
	oCmd.Execute , , 128
	
	
	
	
	If oConn.Errors.Count < 1 then
	
	
	
		Response.Redirect "sel_priceplan_all.asp"
	
		Response.End
	
	else
	
	
	
	
		  strErrMsg = Err.description
		  Err.Clear
	
	
	End If
	
	
	End If
	
	
	If strErrMsg <> "" Then
	
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	
	
	End If %>
	
	
	<form name="thisForm" id="thisForm" method="post" action="addpriceplan.asp">
	
	<STRONG>Price Plan Information</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	*PricePlanName
	
	</td>
	<td>
	
	<input type="text" name="txtPricePlanName" id="txtPricePlanName" MaxLength=20 size=20 Value="<%=PricePlanName%>" >
	
	</td>
	</tr><tr>
	<td>
	
	*Description
	
	</td>
	<td>
	
	<input type="text" name="txtDescription" id="txtDescription" MaxLength=100 size=50 Value="<%=Description%>" >
	
	</td>
	</tr><tr>
	<td>
	
	
	
	</td>
	<td>
	
	<input type="hidden" name="txtCreatedBy" id="txtCreatedBy" Value="<%=CreatedBy%>" >
	
	</td>
	</tr>
	</table><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="submit" border=0 value="Add Price Plan" id=add name=add>
	
	</form>
	* - Required
	
	</body>
	
	</html>
	
</div>
</body>
</html>
