<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home"
%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"     "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Friday, March 08, 2002  22:24:15
	'* Copyright (c) 2002 Team Resources, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: YES
	'* Purpose: This ASP page calls the stored procedure sel_v_Reseller_ConsumerCo using ADO.
	'**********************************************************************************************************************************
	
	
	on error resume next
	
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	
	bSubmitted = 1 
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim ResellerID, ResellerName
	
	ResellerName = Request.QueryString("NM")
	
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
	
		  ResellerID = Request.QueryString("RID")
	
	
	
	End If
	
	ResellerID = Trim(ResellerID)
	
	
	If bSubmitted <> "" Then
	
		  If ResellerID = "" then 
	
				 strErrMsg = " Please enter a value for - ResellerID"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	<%
	If bSubmitted <> "" AND bFilledOutProperly Then
		Dim oConn
		Dim oCmd
		Dim oRs
	
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRs = CreateObject("ADODB.Recordset")
	
		With oCmd
			  .CommandText = "sel_v_Reseller_ConsumerCo"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
			  .Parameters.Append .CreateParameter("@ResellerID",3, 1,4, ResellerID)
		End With
	
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oRs.CursorLocation = 3
		oRs.Open oCmd, , 0, 1
	
		Dim LastAliasID
		If oConn.Errors.Count < 1 then
			Response.Write "<BR><BR>"
			Response.Write "<STRONG>Alias and Consumer Company Information For Reseller: </STRONG>" & ResellerName
			Response.Write "<BR><BR>"
			Dim Field, nColumns
			If oRs.EOF = FALSE then
				LastAliasID = oRs("AliasCompanyID")
				oRs.MoveFirst
				Response.Write "<TABLE BORDER=1>"
				Response.Write "<TR>"
				Response.Write "<TD><font size=2><STRONG>Alias Company Name</STRONG>"
				Response.Write "</TD>"
				Response.Write "<TD><font size=2><STRONG>Alias Company Price Plan</STRONG>"
				Response.Write "</TD>"
				Response.Write "<TD><font size=2><STRONG>Consumer Company Name</STRONG>"
				Response.Write "</TD>"
				Response.Write "<TD><font size=2><STRONG>Consumer Company Price Plan</STRONG>"
				Response.Write "</TD>"
				Response.Write "<TD><font size=2><STRONG>Consumer Company Address</STRONG>"
				Response.Write "</TD>"
				Response.Write "</TR>"
				do while oRs.EOF = FALSE
					Response.Write "<TR>"
					'if LastAliasCompanyID = oRs("AliasCompanyID") then
					'	Response.Write "<TD>&nbsp;" 
					'	Response.Write "</TD>"
					'else
						Response.Write "<TD><font size=2><a href='editcompany.asp?CID=" & oRs("AliasCompanyID") & "'>" & oRs("AliasCompanyName") & "</a>"
						Response.Write "</TD>"
						LastAliasCompanyID = oRs("AliasCompanyID")
					'end if
					Response.Write "<TD><font size=2><a href='editpriceplan.asp?PPID=" & oRs("AliasCompanyPricePlanID") & "'>" & oRs("AliasCompanyPricePlanName") & "</a>"
					Response.Write "</TD>"
					Response.Write "<TD><font size=2><a href='editcompany.asp?CID=" & oRs("ConsumerCompanyID") & "'>" & oRs("ConsumerCompanyName") & "</a>"
					Response.Write "</TD>"
					Response.Write "<TD><font size=2><a href='editpriceplan.asp?PPID=" & oRs("ConsumerCompanyPricePlanID") & "'>" & oRs("ConsumerCompanyPricePlanName") & "</a>"
					Response.Write "</TD>"
					Response.Write "<TD><FONT Size=2>" & oRs("ConsumerCompanyAddress1") & " " & oRs("ConsumerCompanyCity") & " " & oRs("ConsumerCompanyPostalCode")
					Response.Write "</TD>"
					Response.Write "</TR>"
					oRs.MoveNext
				Loop
				Response.Write "</TABLE>"
			End If
			Response.End
		else
			  strErrMsg = Err.description
			  Err.Clear
		End If
	End If
	
	If strErrMsg <> "" Then
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	End If %>
	
	<form name="thisForm" id="thisForm" method="post" action="trash.asp">
	
	<STRONG>Form Information</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	ResellerID
	
	</td>
	<td>
	
	<input type="text" name="txtResellerID" id="txtResellerID" Value="<%=ResellerID%>" >
	
	</td>
	</tr></table><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="submit" border=0 value="submit" id=add name=add>
	
	</form>
	
	
	</body>
	
	</html>
	
</div>
</body>
</html>
