<%@ Language=VBScript %>
<!--#Include FILE="Include/CheckAdminLogin.asp" -->
<!--#Include FILE="../Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>

<title>DISC Profile System | Home Page</title>
<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="../Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/header.asp" -->
<div class="TopNav">
	<a href="../main.asp?res=<%=intResellerID%>">PDI Home</a>&nbsp;|
	<a href="../logout.asp?res=<%=intResellerID%>">Logout</a>&nbsp;
</div>
<div id="maincontent">
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: John Tisdale
	'* Creation Date: Thursday, October 2, 2002  16:46:35
	'* Copyright (c) 2002 VoyageSoft, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: YES
	'* Purpose: This ASP page calls the stored procedure sel_Purchase_Daily_Summary_Day using ADO.
	'**********************************************************************************************************************************
	
	on error resume next
	
	Dim bSubmitted
	bSubmitted = Request.Form ("txtSubmit")
	Dim bFilledOutProperly, strErrMsg
	Dim Date2
	bFilledOutProperly = FALSE
	If bSubmitted <> "" Then
		  Date2 = Request.Form("txtDate")
	else
		Date2 = CStr(month(now())) + "/" + Cstr(day(now())) + "/" + CStr(year(Now()))  
		'Response.Write Date2
	End If
	Dim SiteID
	SiteID = Request.Form ("txtSiteID")
	
	Date = Trim(Date)
	If bSubmitted <> "" Then
		  If Date2 = "" Then
				 strErrMsg = " Please enter a value for - Date"
		 ElseIf isDate(Date2) = false Then
				 strErrMsg = " Please enter a valid date."
		  Else
				 bFilledOutProperly = TRUE
		  End If
	End If%>
	<html>
	<head>
		<title></title>
	</head>
	<body>
	<form name="thisForm" id="thisForm" method="post" action="accountingDailyReportSite.asp">
	<STRONG>Enter Date</STRONG>
	<br><br>
	Enter date to display accounting numbers. 
	<table>
	<%
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRsSites = CreateObject("ADODB.Recordset")
		With oCmd
			  .CommandText = "sel_Sites"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
		End With
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oRsSites.CursorLocation = 3
		oRsSites.Open oCmd, , 0, 1
		If oConn.Errors.Count < 1 then
			Response.Write "<tr><td>Site</td>"
			Response.Write "<td><select name='txtSiteID'>"
			Do While oRsSites.EOF = FALSE
				Response.Write "<option Value='" & oRsSites("SiteID") & "' "
				If CInt(oRsSites("SiteID")) = CInt(SiteID) Then
					Response.Write "selected"
				End If
				Response.Write ">" & oRsSites("SiteName") & "</option>"
				oRsSites.MoveNext
			Loop
			Response.Write "</select></td></tr>"
		End If
	%>
		<tr>
			<td>*Date</td>
			<td><input type="text" name="txtDate" id="txtDate" Value="<%=Date2%>" ></td>
		</tr>
	</table>
	<br>
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	<input type="submit" border=0 value="submit" id=add name=add>
	</form>
	* - Required
	<%
	If bSubmitted <> "" AND bFilledOutProperly Then
		Dim oConn
		Dim oCmd
		Dim oRs
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRs = CreateObject("ADODB.Recordset")
		With oCmd
			  .CommandText = "sel_DM_Purchase_Daily_Summary_Site_Day"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
			  .Parameters.Append .CreateParameter("@Date",135, 1,16, Date2)
				.Parameters.Append .CreateParameter("@SiteID",3, 1,4, SiteID)
		End With
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oRs.CursorLocation = 3
		oRs.Open oCmd, , 0, 1
		If oConn.Errors.Count < 1 then
			Response.Write "<BR><BR>"
			Dim Field, nColumns
			Response.Write "<TABLE BORDER=1>"
			Response.Write "<TR>"
			Response.Write "	<TD><STRONG>Total Purchases</STRONG></TD>"
			Response.Write "	<TD><STRONG>Total Discounts</STRONG></TD>"
			Response.Write "	<TD><STRONG>Total Commissions</STRONG></TD>"
			Response.Write "</TR>"
			If oRs.EOF = FALSE then
				oRs.MoveFirst
				do while oRs.EOF = FALSE
					Response.Write "<TR>"
					Response.Write "	<TD ALIGN=RIGHT>" & FormatCurrency(oRs("TotalPurchases"),2) & "</TD>"
					Response.Write "	<TD ALIGN=RIGHT>" & FormatCurrency(oRs("TotalDiscounts"),2) & "</TD>"
					Response.Write "	<TD ALIGN=RIGHT>" & FormatCurrency(oRs("TotalCommissions"),2) & "</TD>"
					Response.Write "</TR>"
					oRs.MoveNext
				Loop
			End If
			Response.Write "</TABLE>"
			Response.End
		Else
			  strErrMsg = Err.description
			  Err.Clear
		End If
	End If
	If strErrMsg <> "" Then
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	End If %>
	</body>
	</html>
</div>
</body>
</html>
