<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Thursday, January 17, 2002  17:22:04
	'* Copyright (c) 2002 VoyageSoft, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure upd_UserInfo using ADO.
	'******************************************************************************************
	
	on error resume next
	
	Dim bSubmitted
	bSubmitted = Request.Form ("txtSubmit")
	
	Dim bFilledOutProperly, strErrMsg
	Dim FirstName
	Dim LastName
	Dim Postition
	Dim TeamName
	Dim Department
	Dim EmailAddress
	Dim UserTypeID
	Dim Active
	Dim LastModifiedBy
	Dim UserID
	
	bFilledOutProperly = FALSE
	If bSubmitted <> "" Then
		  FirstName = Request.Form("txtFirstName")
		  LastName = Request.Form("txtLastName")
		  Postition = Request.Form("txtPostition")
		  TeamName = Request.Form("txtTeamName")
		  Department = Request.Form("txtDepartment")
		  EmailAddress = Request.Form("txtEmailAddress")
		  UserTypeID = Request.Form("txtUserTypeID")
		  Active = Request.Form("txtActive")
		  If Active = "on" then
			Active = 1
		  else
			Active = 0
		  end if
		  LastModifiedBy = Request.Form("txtLastModifiedBy")
		  UserID = Request.Form("txtUserID")
	Else
		LastModifiedby = Request.Cookies("UserID")
		UserID = Request.QueryString("UID")
		' Don't allow the user to edit their own information on this page
		If UserID = Request.Cookies("UserID") Then
			Response.Write "<br><br>"
			Response.Write "This page is for editing other user's information. To edit your own informatoin please see the other <a href='edituser.asp'>edit user page.</a>"
			Response.End
		End if
		' now get the user information
		Dim oConn
		Dim oCmd
		Dim oRs
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRs = CreateObject("ADODB.Recordset")
		With oCmd
			  .CommandText = "sel_UserInfo_UserID"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
				.Parameters.Append .CreateParameter("@UserID",3, 1,4, UserID)
		End With
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oRs.CursorLocation = 3
		oRs.Open oCmd, , 0, 1
		If oConn.Errors.Count > 0  then
			Response.Write "Error retrieving user information."
			Response.End
		end if
		FirstName = oRs("FirstName")
		LastName = oRs("LastName")
		Postition = oRs("Postition")
		TeamName = oRs("TeamName")
		Department = oRs("Department")
		EmailAddress = oRs("EmailAddress")
		UserTypeID = oRs("UserTypeID")
		Active = oRs("Active")
		UserID = oRs("UserID")
		Set oConn = nothing
		Set oCmd = nothing
		Set oRs = nothing
	End If
	
	FirstName = Trim(FirstName)
	LastName = Trim(LastName)
	Postition = Trim(Postition)
	TeamName = Trim(TeamName)
	Department = Trim(Department)
	EmailAddress = Trim(EmailAddress)
	UserTypeID = Trim(UserTypeID)
	Active = Trim(Active)
	LastModifiedBy = Trim(LastModifiedBy)
	UserID = Trim(UserID)
	
	If bSubmitted <> "" Then
		  If FirstName = "" then
				 strErrMsg = " Please enter a value for - FirstName"
		  ElseIf LastName = "" then
				 strErrMsg = " Please enter a value for - LastName"
		  'ElseIf Postition = "" then
				 'strErrMsg = " Please enter a value for - Postition"
		  'ElseIf TeamName = "" then
				 'strErrMsg = " Please enter a value for - TeamName"
		  'ElseIf Department = "" then
				 'strErrMsg = " Please enter a value for - Department"
		  ElseIf EmailAddress = "" then
				 strErrMsg = " Please enter a value for - EmailAddress"
		  ElseIf UserTypeID = "" then
				 strErrMsg = " Please enter a value for - UserTypeID"
		  ElseIf Active = "" then
				 strErrMsg = " Please enter a value for - Active"
		  ElseIf LastModifiedBy = "" then
				 strErrMsg = " Please enter a value for - LastModifiedBy"
		  ElseIf UserID = "" then
				 strErrMsg = " Please enter a value for - UserID"
		  Else
				 bFilledOutProperly = TRUE
		  End If
	End If%>
	<html>
	<head>
	<title></title>
	</head>
	<body>
	<%
	If bSubmitted <> "" AND bFilledOutProperly Then
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		With oCmd
		  .CommandText = "upd_UserInfo"
		  .CommandType = 4
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
		  .Parameters.Append .CreateParameter("@FirstName",200, 1,100, FirstName)
		  .Parameters.Append .CreateParameter("@LastName",200, 1,100, LastName)
		  .Parameters.Append .CreateParameter("@Postition",200, 1,100, Postition)
		  .Parameters.Append .CreateParameter("@TeamName",200, 1,50, TeamName)
		  .Parameters.Append .CreateParameter("@Department",200, 1,50, Department)
		  .Parameters.Append .CreateParameter("@EmailAddress",200, 1,100, EmailAddress)
		  .Parameters.Append .CreateParameter("@UserTypeID",3, 1,4, UserTypeID)
		  .Parameters.Append .CreateParameter("@Active",3, 1,4, Active)
		  .Parameters.Append .CreateParameter("@LastModifiedBy",3, 1,4, LastModifiedBy)
		  .Parameters.Append .CreateParameter("@UserID",3, 1,4, UserID)
		End With
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oCmd.Execute , , 128
		If oConn.Errors.Count < 1 then
			Response.Write "<BR><BR>User information updated successfully.<BR><BR>"
			Response.End
		Else
			strErrMsg = Err.description
			Err.Clear
		End If
	End If
	If strErrMsg <> "" Then
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	End If %>
	
	<form name="thisForm" id="thisForm" method="post" action="edituser_int.asp">
	
	<br><br>
	
	<STRONG>Edit User Information</STRONG>
	
	<br><br>
	<table>
		<tr>
			<td>*First Name</td>
			<td><input type="text" name="txtFirstName" id="txtFirstName" MaxLength=100 Size=50 Value="<%=FirstName%>" ></td>
		</tr>
		<tr>
			<td>*Last Name</td>
			<td><input type="text" name="txtLastName" id="txtLastName" MaxLength=100 Size=50 Value="<%=LastName%>" ></td>
		</tr>
		<tr>
			<td>Position</td>
			<td><input type="text" name="txtPostition" id="txtPostition" MaxLength=100 Size=50 Value="<%=Postition%>" ></td>
		</tr>
		<tr>
			<td>Team Name</td>
			<td><input type="text" name="txtTeamName" id="txtTeamName" MaxLength=50 Value="<%=TeamName%>" ></td>
		</tr>
		<tr>
			<td>Department</td>
			<td><input type="text" name="txtDepartment" id="txtDepartment" MaxLength=50 Value="<%=Department%>" ></td>
		</tr>
		<tr>
			<td>*Email Address</td>
			<td><input type="text" name="txtEmailAddress" id="txtEmailAddress" MaxLength=100 Size=50 Value="<%=EmailAddress%>" ></td>
		</tr>
		<tr>
			<td>*User Type</td>
			<td>
	<%
	Set oConn = CreateObject("ADODB.Connection")
	Set oCmd = CreateObject("ADODB.Command")
	Set oRs = CreateObject("ADODB.Recordset")
	With oCmd
		  .CommandText = "sel_UserType_all"
		  .CommandType = 4
		  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
	End With
	oConn.Open strDbConnString
	oCmd.ActiveConnection = oConn
	oRs.CursorLocation = 3
	oRs.Open oCmd, , 0, 1
	If oConn.Errors.Count < 1 then
		%>
		<select name="txtUserTypeID">
		<%
			while oRs.EOF = FALSE
				if CInt(oRs("UserTypeID")) = CInt(UserTypeID) then
				%>
					<option value="<%=oRs("UserTypeID")%>" selected><%=oRs("UserType")%>
				<% else %>
					<option value="<%=oRs("UserTypeID")%>"><%=oRs("UserType")%>
				<%
				end if
				oRs.MoveNext
			wend
	end if
	Set oConn = Nothing
	Set oCmd = Nothing
	Set oRs = Nothing
	%>
	</select>
			</td>
		</tr>
		<tr>
			<td>*Active</td>
			<td>
	<% if Active = 1 then %>
		<input type="checkbox" CHECKED name="txtActive" id="txtActive" >
	<% else %>
		<input type="checkbox" name="txtActive" id="txtActive" >
	<% end if %>
			</td>
		</tr>
		<tr>
			<td></td>
			<td><input type="hidden" name="txtLastModifiedBy" id="txtLastModifiedBy" Value="<%=LastModifiedBy%>" ></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="hidden" name="txtUserID" id="txtUserID" Value="<%=UserID%>" ></td>
		</tr>
	</table>
	<br>
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	<input type="submit" border=0 value="submit" id=add name=add>
	</form>
	<br>
	* - Required
	</body>
	</html>
</div>
</body>
</html>
