<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Wednesday, January 23, 2002  00:54:56
	'* Copyright (c) 2002 VoyageSoft, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: YES
	'* Purpose: This ASP page calls the stored procedure sel_Company_Users using ADO.
	'**********************************************************************************************************************************
	
	on error resume next
	
	
	Dim bSubmitted, nFontSize, CompanyName
	
	nFontSize = 2
	
	'bSubmitted = Request.Form ("txtSubmit")
	
	bSubmitted = 1
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim CompanyID
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
	
		  CompanyID = Request.QueryString("CID")
		  CompanyName = Request.QueryString("NM")
		  
	
	End If
	
	CompanyID = Trim(CompanyID)
	
	
	If bSubmitted <> "" Then
	
		  If CompanyID = "" then 
	
				 strErrMsg = " Please enter a value for - CompanyID"
	
		  Else
	
				 bFilledOutProperly = TRUE
	
		  End If
	
	End If%>
	
	
	<html>
	
	<head>
	
	<title></title>
	
	</head>
	
	<body>
	
	
	
	<%
	
	
	If bSubmitted <> "" AND bFilledOutProperly Then
	
		Dim oConn
	
		Dim oCmd
	
	
		Dim oRs
	
	
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRs = CreateObject("ADODB.Recordset")
	
	
	
		With oCmd
	
			  .CommandText = "sel_Company_Users"
			  .CommandType = 4
	
	
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
							 .Parameters.Append .CreateParameter("@CompanyID",3, 1,4, CompanyID)
	
	
	
		End With
	
	
	
	
		oConn.Open strDbConnString
	
		oCmd.ActiveConnection = oConn
	
	
		oRs.CursorLocation = 3
	
		oRs.Open oCmd, , 0, 1
	
		If oConn.Errors.Count < 1 then
	
	
			Response.Write "<BR><BR><STRONG>" & CompanyName & "</STRONG>"

	
			Response.Write "<BR><BR>"
			Response.Write "<STRONG>No. of Users: " & oRs.RecordCount
			Response.Write "</STRONG><BR><BR>"
			
			Dim Field, nColumns
	
			If oRs.EOF = FALSE then
				oRs.MoveFirst
	
				Response.Write "<TABLE BORDER=1>"
	
				Response.Write "<TR>"
	
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Last Name</STRONG>"
				Response.Write "</TD>"
	
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>First Name</STRONG>"
				Response.Write "</TD>"
				
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>UserName</STRONG>"
				Response.Write "</TD>"
	
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Email Address</STRONG>"
				Response.Write "</TD>"
	
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Position</STRONG>"
				Response.Write "</TD>"
				
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Team Name</STRONG>"
				Response.Write "</TD>"
				
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Department</STRONG>"
				Response.Write "</TD>"
				
				Response.Write "<TD><FONT SIZE=" & nFontSize & "><STRONG>Active</STRONG>"
				Response.Write "</TD>"
				
				Response.Write "</TR>"
	
				do while oRs.EOF = FALSE
	
					Response.Write "<TR>"
	
					Response.Write "<TD><a href='edituser_int.asp?UID=" & oRs("UserID") & "'><FONT SIZE=" & nFontSize & ">" & oRs("LastName") & "</a>"
					Response.Write "</TD>"
	
					Response.Write "<TD><FONT SIZE=" & nFontSize & ">" & oRs("FirstName")
					Response.Write "</TD>"
				
					Response.Write "<TD><FONT SIZE=" & nFontSize & ">" & oRs("UserName")
					Response.Write "</TD>"
	
					Response.Write "<TD><A HREF='mailto:" & oRs("EmailAddress") & "'><FONT SIZE=" & nFontSize & ">" & oRs("EmailAddress") & "</a>"
					Response.Write "</TD>"
	
					Response.Write "<TD><FONT SIZE=" & nFontSize & ">" & oRs("Postition")
					Response.Write "</TD>"
				
					Response.Write "<TD><FONT SIZE=" & nFontSize & ">" & oRs("TeamName")
					Response.Write "</TD>"
				
					Response.Write "<TD><FONT SIZE=" & nFontSize & ">" & oRs("Department")
					Response.Write "</TD>"
				
					Response.Write "<TD>"
					
					
					
					
					if oRs("Active") = 1 then
						Response.Write "YES"
					else
						Response.Write "NO"
					end if
				
					Response.Write "</TD>"
				
					Response.Write "</TR>"
	
					oRs.MoveNext
	
				Loop
	
				Response.Write "</TABLE>"
	
			End If
	
	
	
			Response.End
	
		else
	
			  strErrMsg = Err.description
			  Err.Clear
	
		End If
	
	End If
	
	
	If strErrMsg <> "" Then
	
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	
	
	End If %>
	
	
	<form name="thisForm" id="thisForm" method="post" action="trash.asp">
	
	<STRONG>Form Information</STRONG>
	
	<br><br>
	
	<table>
	
	<tr>
	<td>
	
	CompanyID
	
	</td>
	<td>
	
	<input type="text" name="txtCompanyID" id="txtCompanyID" Value="<%=CompanyID%>" >
	
	</td>
	</tr></table><br>
	
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	
	<input type="submit" border=0 value="submit" id=add name=add>
	
	</form>
	
	
	</body>
	
	</html>
	

</div>
</body>
</html>
