<%@ Language=VBScript %>
<!--#Include FILE="Include/checklogin.asp" -->
<!--#Include FILE="Include/common.asp" -->
<% pageID = "home" %>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
	<title>DISC Profile System | Home Page</title>
	<meta name="generator" content="BBEdit 7.0.1">
	<link rel="stylesheet" href="Include/Default.css" type="text/css">
	<link rel="stylesheet" href="/RS/<%=SitePathName%>/Reseller.css" type="text/css">
	<!--#Include FILE="Include/HeadStuff.asp" -->	
</head>
<body>
<!--#Include FILE="Include/TopBanner.asp" -->

<div id="maincontent">
	<%
	'*****************************************************************************************
	'*
	'* Generated By: TierBuilder V3.2 - www.tierbuilder.com
	'* Created By: David Brackin
	'* Creation Date: Wednesday, January 16, 2002  20:30:39
	'* Copyright (c) 2002 VoyageSoft, Inc.
	'*
	'* ----  Code Settings ----
	'*
	'* Returns Recordset: NO
	'* Purpose: This ASP page calls the stored procedure upd_PricePlanDetail using ADO.
	'**********************************************************************************************************************************
	
	on error resume next
	
	Dim bSubmitted
	
	bSubmitted = Request.Form ("txtSubmit")
	
	Dim bFilledOutProperly, strErrMsg
	
	Dim PricePlanID
	Dim MinVolumeAmt
	Dim MaxVolumeAmt
	Dim DiscountPercent
	Dim CommissionPercent
	Dim LastModifiedBy
	Dim PricePlanDetailID
	Dim RelatedToReseller
	
	bFilledOutProperly = FALSE
	
	If bSubmitted <> "" Then
		  PricePlanID = Request.Form("txtPricePlanID")
		  MinVolumeAmt = Request.Form("txtMinVolumeAmt")
		  MaxVolumeAmt = Request.Form("txtMaxVolumeAmt")
		  DiscountPercent = Request.Form("txtDiscountPercent")
		  CommissionPercent = Request.Form("txtCommissionPercent")
		  LastModifiedBy = Request.Form("txtLastModifiedBy")
		  PricePlanDetailID = Request.Form("txtPricePlanDetailID")
	else
		PricePlanDetailID = Request.QueryString("PPDID")
		LastModifiedBy = Request.Cookies("UserID")
		' retrieve the data to update
		Dim oConn
		Dim oCmd
		Dim oRs
	
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
		Set oRs = CreateObject("ADODB.Recordset")
	
		With oCmd
			  .CommandText = "sel_PricePlanDetail"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
				.Parameters.Append .CreateParameter("@PricePlanDetailID",3, 1,4, PricePlanDetailID)
		End With
	
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oRs.CursorLocation = 3
		oRs.Open oCmd, , 0, 1
	
		If oConn.Errors.Count < 1 then
			MinVolumeAmt = oRs("MinVolumeAmt")
			MaxVolumeAmt = oRs("MaxVolumeAmt")
			DiscountPercent = oRs("DiscountPercent")
			CommissionPercent = oRs("CommissionPercent")
			PricePlanID = oRs("PricePlanID")
			RelatedToReseller = oRs("RelatedToReseller")
		End If
	End If
	
	PricePlanID = Trim(PricePlanID)
	MinVolumeAmt = Trim(MinVolumeAmt)
	MaxVolumeAmt = Trim(MaxVolumeAmt)
	DiscountPercent = Trim(DiscountPercent)
	CommissionPercent = Trim(CommissionPercent)
	LastModifiedBy = Trim(LastModifiedBy)
	PricePlanDetailID = Trim(PricePlanDetailID)
	
	If bSubmitted <> "" Then
		  If PricePlanID = "" then 
				 strErrMsg = " Please enter a value for - PricePlanID"
		  ElseIf MinVolumeAmt = "" then 
				 strErrMsg = " Please enter a value for - MinVolumeAmt"
		  ElseIf MaxVolumeAmt = "" then 
				 strErrMsg = " Please enter a value for - MaxVolumeAmt"
		  ElseIf DiscountPercent = "" then 
				 strErrMsg = " Please enter a value for - DiscountPercent"
		 ElseIf DiscountPercent >= 1.0 then 
				 strErrMsg = " Please enter a value less than 1 for DiscountPercent"
		  ElseIf CommissionPercent = "" then 
				 strErrMsg = " Please enter a value for - CommissionPercent"
		 ElseIf DiscountPercent >= 1.0 then 
				 strErrMsg = " Please enter a value less than 1 for CommissionPercent"
		  ElseIf LastModifiedBy = "" then 
				 strErrMsg = " Please enter a value for - LastModifiedBy"
		  ElseIf PricePlanDetailID = "" then 
				 strErrMsg = " Please enter a value for - PricePlanDetailID"
		  Else
				 bFilledOutProperly = TRUE
		  End If
	End If%>
	
	<html>
	<head>
		<title></title>
	</head>
	<body>
	<%
	If bSubmitted <> "" AND bFilledOutProperly Then
		Set oConn = Nothing
		Set oCmd = Nothing
		Set oConn = CreateObject("ADODB.Connection")
		Set oCmd = CreateObject("ADODB.Command")
	
		With oCmd
			  .CommandText = "upd_PricePlanDetail"
			  .CommandType = 4
			  .Parameters.Append .CreateParameter("@RETURN_VALUE", 3, 4, 0)
			  .Parameters.Append .CreateParameter("@PricePlanID",3, 1,4, PricePlanID)
			  .Parameters.Append .CreateParameter("@MinVolumeAmt",6, 1,21, MinVolumeAmt)
			  .Parameters.Append .CreateParameter("@MaxVolumeAmt",6, 1,21, MaxVolumeAmt)
			  .Parameters.Append .CreateParameter("@DiscountPercent",5, 1,8, DiscountPercent)
			  .Parameters.Append .CreateParameter("@CommissionPercent",5, 1,8, CommissionPercent)
			  .Parameters.Append .CreateParameter("@LastModifiedBy",3, 1,4, LastModifiedBy)
			  .Parameters.Append .CreateParameter("@PricePlanDetailID",3, 1,4, PricePlanDetailID)
		End With
	
		oConn.Open strDbConnString
		oCmd.ActiveConnection = oConn
		oCmd.Execute , , 128
	
		If oConn.Errors.Count < 1 then
			Response.Redirect("editpriceplan.asp?PPID=" & PricePlanID)
			Response.End
		else
			  strErrMsg = Err.description
			  Err.Clear
		End If
	End If
	
	If strErrMsg <> "" Then
		  Response.Write "<br>"
		  Response.Write strErrMsg
		  Response.Write "<br><br>"
	End If %>
	
	<form name="thisForm" id="thisForm" method="post" action="editpriceplandetail.asp">
	<br>
	<STRONG>Edit Price Plan Details</STRONG>
	
	<br><br>
	
	<% if CInt(RelatedToReseller) = 1 then %>
	
	<strong>
	<font color=red>This price plan is related to a reseller. </font><br>
	</strong>
	<br><br>
	<% end if %>
	
	<table>
		<tr>
			<td></td>
			<td><input type="hidden" name="txtPricePlanID" id="txtPricePlanID" Value="<%=PricePlanID%>" ></td>
		</tr>
		<tr>
			<td>*MinVolumeAmt</td>
			<td><input type="text" name="txtMinVolumeAmt" id="txtMinVolumeAmt" Value="<%=MinVolumeAmt%>" ></td>
		</tr>
		<tr>
			<td>*MaxVolumeAmt</td>
			<td><input type="text" name="txtMaxVolumeAmt" id="txtMaxVolumeAmt" Value="<%=MaxVolumeAmt%>" ></td>
		</tr>
		<tr>
			<td>*DiscountPercent</td>
			<td><input type="text" name="txtDiscountPercent" id="txtDiscountPercent" Value="<%=DiscountPercent%>" ></td>
		</tr>
		<tr>
			<td>*CommissionPercent</td>
			<td><input type="text" name="txtCommissionPercent" id="txtCommissionPercent" Value="<%=CommissionPercent%>" ></td>
		</tr>
		<tr>
			<td></td>
			<td><input type="hidden" name="txtLastModifiedBy" id="txtLastModifiedBy" Value="<%=LastModifiedBy%>" ></td>
		</tr>
		<tr>
			<td></td>
			<td>
				<input type="hidden" name="txtPricePlanDetailID" id="txtPricePlanDetailID" Value="<%=PricePlanDetailID%>" >
				<input type="hidden" name="txtRelatedToReseller" id="txtRelatedToReseller" Value="<%=RelatedToReseller%>" >
			</td>
		</tr>
	</table><br>
	<input type="hidden" name="txtSubmit" id="txtSubmit" value=1>
	<input type="button" border=0 value="Update" id=add name=add onClick="formsubmitted()">
	</form>
	* - Required
	
	</body>
	</html>
	
	
	<script language="Javascript">
	<!--
	function formsubmitted() 
	{
		if(document.thisForm.txtCommissionPercent.value < .0001)
		{
			if(document.thisForm.txtRelatedToReseller.value == 0)
			{
				//document.thisForm.target = "editpriceplandetail.asp";
				document.thisForm.submit();
			}
			else // make sure the user wishes to make this change
			{
				var x=window.confirm("This price plan is related to a reseller. Are you sure you wish to set commission percent to zero?")
				
				if(x)
				{
					//document.thisForm.target = "editpriceplandetail.asp";
					document.thisForm.submit();
				}						
			}
		}
		else
		{
			//document.thisForm.target = "editpriceplandetail.asp";
			document.thisForm.submit();
		}
	} 
	// -->
	</script>

</div>
</body>
</html>
