<table width="100%" border="0" cellspacing="0" cellpadding="0">
  <tr bgcolor="#FFFFFF"> 
    <td colspan="4"><img src="rs/medquist/trans_shim.gif" width="5" height="1"></td>
  </tr>
  <tr> 
    <td colspan="4" class="dk"><img src="rs/medquist/trans_shim.gif" width="5" height="1"></td>
  </tr>
  <tr> 
    <td width="137" class="mid"><a name="top"></a><img src="rs/medquist/top_nav_triangles.gif" width="137" height="17"></td>
    <td width="100%" colspan="3" class="mid" valign="top">&nbsp;</td>
  </tr>
  <tr> 
    <td colspan="4" class="dk"><img src="rs/medquist/trans_shim.gif" width="5" height="1"></td>
  </tr>
  <tr bgcolor="#FFFFFF"> 
    <td colspan="4"><img src="rs/medquist/trans_shim.gif" width="5" height="1"></td>
  </tr>
</table>
<div style="float:left"><img src="rs/medquist/medquist_logo.gif" /></div>