<table align="center" width="900" border="0">
<tr><td>&nbsp;</td></tr>
<tr><td align="center"><h1>Welcome to the Medquist DISC Assessment</h1>
</td></tr>
<tr><td align="center" style="padding-left:100px;padding-right:100px">
On the next pages you will register and take the Personal DISCernment Inventory assessment.
Please ensure that you enter a valid email address. This address will be used to mail your
reports to you.
</td></tr>
</table>